### ISSUE TITLE
nextcloud-security-scan: Should we report on Header Warnings, too?

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#106]
In GitLab by @markuslf on Jun 11, 2020, 08:31

Currently check throws a warning if overall rating is below A/B. Should we also warn on "Header X-Frame-Options missing. Header X-Content-Type-Options missing."?

**Comment by markuslf** [comment]
Would be a separate check for HTTP Security Headers, maybe using Scott Helme's [securityheaders.com](https://securityheaders.com/)
