### ISSUE TITLE
updates: make this check also aware of "apt"

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#176]
In GitLab by @markuslf on Apr 16, 2021, 10:37

**Comment by markuslf** [comment]
As of today, we have:
* https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/updates for Windows
* https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/rpm-lastactivity for yum/dnf-based systems
* https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/deb-lastactivity for apt-based systems
