### ISSUE TITLE
Simplify Installation in any way

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#300]
Python `setup.py` with something like a `requirements.txt`? https://docs.python.org/3/distutils/setupscript.html, `pip3 install -r /path/to/requirements.txt`

Bash script? Something like `curl https://git.linuxfabrik.ch/path/to/install.sh | sudo bash`?

should:
* download the monitoring-plugins and lib repos (`curl`)
* copy the checks and lib to the right directory
* if `icingacli director` is available, import all the command definitions (make sure that this will not break the existing config)
* deploy the correct sudoers
* handle upgrades
* throw human readable errors

should use a default PYVER and default to the `master` branch, but accept those as options

**Comment by fl0wx** [comment]
+1 for debian package :)

**Comment by markuslf** [comment]
Sounds like there's definitely a need for a Linuxfabrik repo server, based on [fpm](https://github.com/jordansissel/fpm) or something similar.

**Comment by markuslf** [comment]
If installing third party libs like _psutil_ using package managers, we have to keep this in mind:

# Third-party packages

Not all Python software is shipped with RHEL 8 – there's only so much that Red Hat can verify, package and support.

To install a third-party package, many sources on the Internet will suggest using sudo pip install. Do not do this! This command translates to “download a package from the internet, and run it on my machine as root to install it”.

Even if the package is trustworthy, this is a bad idea. A large part of RHEL 8 relies on Python 3.6. If you throw in another package, there's no guarantee that it will co-exist peacefully with the rest of the system. There are some protections in place, but you should generally assume that sudo pip will break your system.

(Not to mention it won’t work as-is: the command name is pip3 or pip2.)

If you want to use third-party packages, create a virtual environment using python3 -m venv --system-site-packages myenv (or for Python 2, install python2-virtualenv and run python2 -m virtualenv --system-site-packages myenv). Then, activate the environment using source myenv/bin/activate, and install packages into it using pip install. The packages will then be available as long as the environment is activated. While this does not protect you against malicious packages, it does protect the system from unexpected breakage.

When a virtual environment is active, unversioned commands like python and pip will refer to the Python version that created the virtual environment. So, to install the Requests package, run  pip install requests (or if you prefer being explicit, python -m pip install requests).

The --system-site-packages switch makes the environment re-use libraries installed system-wide. Leave it out to get an isolated environment, where all libraries outside Python's standard library need to be installed explicitly.

Another possibility is installing user-specific packages with pip’s --user switch. The command python3 -m pip install --user flake8 will make the flake8 linter available to you personally, leaving system tools like yum unaffected.

If you truly need something installed system-wide, build a RPM package and use yum install.

Obligatory note: Third-party packages installed with pip are not reviewed or supported by Red Hat. 


https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8-3#why_not_just__python__

**Comment by markuslf** [comment]
RPM or DEB file will do a complete low-level installation including Python psutil (not with pip), like glances does. There will be no dependency on EPEL or similar.

**Comment by markuslf** [comment]
We will implement this as follows:
* Compile all plugins including all Linuxfabrik and 3rd party libraries so that a Python environment is no longer needed on the target host.
* Create installation packages with fpm (targets are rpm, deb, etc.) that install the binaries.

**Comment by NavidSassan** [comment]
done :) https://repo.linuxfabrik.ch/monitoring-plugins/
