### ISSUE TITLE
qts-temperature: Is it correct to have one value for CPU and System Temperature Threshold?

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#313]
In GitLab by @markuslf on Jul 15, 2021, 11:57

Normally a CPU threshold could be higher than a System (Case) temperature.

**Comment by sandrolf** [comment]
```
./qts-temperatures --url http://192.168.123.123:8080 --password **********
Sys: 31°C, CPU: 58°C|'systemp'=31;70;80;0; 'cputemp'=58;70;80;0;
```

**Comment by markuslf** [comment]
This is of course not correct. Corrected, and even better: Temperature thresholds are determined automatically.
