### ISSUE TITLE
Implement a new and cleaner directory structure

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#350]
In GitLab by @markuslf on Aug 31, 2021, 16:50

Before the next release, let's move some files to new locations. A check plugin directory should look like this from that on:

```
└── plugin-name
    ├── assets
    │   └── Additional ressources, for example helper scripts like monitoring.php
    ├── grafana
    │   └── dashboard definition
    ├── icingaweb2-module-director
    │   └── Icinga Director basket definition
    ├── icingaweb2-module-grafana
    │   └── Grafana panel definition for Icinga's Grafana module
    ├── lib
    └── unit-test
        ├── stdin
        └── stdout
```

The plugins' main directory will contain the check (Python 3) and README file only.

* [x] Explain this structure in README.
* [ ] Adapt LFOps for Grafana Deployment

**Comment by markuslf** [comment]
See also https://github.com/Linuxfabrik/monitoring-plugins/issues/589
