### ISSUE TITLE
Dealing with default values - how to deactivate default values?

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#352]
In GitLab by @markuslf on Sep 2, 2021, 17:00

In CONTRIBUTING, specify how to deactivate the default values we have defined, if desired - for all parameter types (especially interesting for "repeating"). Use dmesg and systemd-unit as an example.

Currently discussed:
* using a magic keyword value like `--my-param=None` or `--my-param=__NONE__`
* using a `--my-param-no-defaults` or a more global `--no-defaults` toggle

Some customers are also interested in this.

**Comment by markuslf** [comment]
Even easier, according to https://bugs.python.org/issue16399: _The simplest alternative to this behavior is to leave the default as None. If after parsing the value is still None, put the desired list (or any other object) there. The primary purpose of the parser is to parse the commandline - to figure out what the user wants to tell you. There's nothing wrong with tweaking (and checking) the `args` Namespace after parsing._

That's correct.

Old code example:

```
    parser.add_argument(
        '--module',
        help='"modulename" to check (startswith), for example `--module json --module mbstring` (repeating)',
        dest='MODULES',
        action='append',
        default=DEFAULT_MODULES,
    )

    ....

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

```

New code example:

```
    parser.add_argument(
        '--module',
        help='"modulename" to check (startswith), for example `--module json --module mbstring` (repeating)',
        dest='MODULES',
        action='append',
        default=None,
    )

    ....

    # parse the command line, exit with UNKNOWN if it fails
    try:
        args = parse_args()
    except SystemExit:
        sys.exit(STATE_UNKNOWN)

    # if after parsing the value is None, put the desired defaults there
    if args.MODULES is None:
        args.MODULES = DEFAULT_MODULES

```
