### ISSUE TITLE
gitlab: check last backup

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#39]
In GitLab by @markuslf on Feb 20, 2020, 09:46

* https://docs.gitlab.com/ee/api/
* https://docs.gitlab.com/ee/api/version.html
* https://packages.gitlab.com/app/gitlab/gitlab-ce/search?dist=el%2F7&page=4
* https://packagecloud.io/docs/api

No need to check on latest gitlab version.

**Comment by markuslf** [comment]
Using file-age is good.
