### ISSUE TITLE
README.rst: explain "How to install checks into Icinga"? (all or just one)

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#40]
In GitLab by @markuslf on Feb 21, 2020, 11:06

- Check
- Basket
- PNG
- Grafana

**Comment by Domi-cc** [comment]
i really have problems to import the baskets on a fresh installation.

where for example is the tpl-generic-template? isn't there a complete basket file with all the stuff? or maybe i am blind :)

**Comment by Domi-cc** [comment]
this is the missing link here: https://docs.linuxfabrik.ch/monitoring-plugins/000-check-plugins.html#linuxfabrik-s-director-configuration

**Comment by markuslf** [comment]
I tried to be more specific. Have a look at the [updated README here](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/README.md).
