### ISSUE TITLE
Windows: New ServiceSet for Windows-Servers running "Veeam Backup & Replication"

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#464]
In GitLab by @markuslf on Nov 15, 2021, 11:08

`service`:

* Veeam AWS Service: `--service VeeamAWSSvc --status running --starttype automatic`
* Veeam Azure Service: `--service VeeamAzureSvc --status running --starttype automatic`
* Veeam Backup Server RESTful API Service: `--service VeeamBackupRESTSvc --status running --starttype automatic`
* Veeam Backup VSS Integration Service: `--service VeeamFilesysVssSvc --status running --starttype automatic`
* Veeam Data Mover Service: `--service VeeamTransportSvc --status running --starttype automatic`
* Veeam Explorers Recovery Service: `--service VeeamExplorersRecoverySvc --status running --starttype automatic`
* Veeam Installer Service: `--service VeeamDeploySvc --status running --starttype automatic`
* Veeam Mount Service: `--service VeeamMountSvc --status running --starttype automatic`
* Veeam vPower NFS Service: `--service VeeamNFSSvc --status running --starttype automatic`

**Comment by laison007** [comment]
Is this set for veeam compatible with 64 bit systems? Because I am trying to implement it and I get that the service.exe program is not compatible with 64 bit systems.
I have used the service file from the directory "check-plugins".

I get an error window that says "16-bit application not supported".

**Comment by markuslf** [comment]
Please open a new issue for this.
