### ISSUE TITLE
check2basket: do not adjust datafield_ids if not necessary

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#479]
this reduces the changes in commits

**Comment by markuslf** [comment]
What to do on this issue depends on what's all about with the new UUIDs in Icinga Director.

**Comment by markuslf** [comment]
I think we fixed that with https://github.com/Linuxfabrik/monitoring-plugins/commit/21f4fbde738ada4f7d3c8fdea19384ee4a893ec0, but we just forgot to close this issue.
