### ISSUE TITLE
Basket restore in Icinga Director fails "Trying to set invalid key "guid" (DbObject.php:350)"

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#493]
In GitLab by @fesch on Jan 12, 2022, 10:48

If I try to restore the imported Basket in Icinga Director I get the following error "Trying to set invalid key "guid" (DbObject.php:350)".
The file "icingaweb2-module-director-basket.json" was created with the command "./tools/basket-join --without-guids".

**Comment by agougo** [comment]
I am also facing the exact issue on the LinuxFabrik Logfile plugin

![image](https://user-images.githubusercontent.com/8976509/161047306-c3e9ed40-3fa1-484e-af3b-96784c29f601.png)

**Comment by NavidSassan** [comment]
@agougo just to make sure, did you use the `./tools/basket-join --without-guids` option to create the basket?

**Comment by agougo** [comment]
@NavidSassan - ok, now i see what you mean. I tried to recreate the json file with ./tools/basket-join --without-guids - the error is the same

**Comment by NavidSassan** [comment]
can you upload the json file that you are trying to import?

**Comment by agougo** [comment]
Here you are

[logfile.json.txt](https://github.com/Linuxfabrik/monitoring-plugins/files/8391238/logfile.json.txt)

**Comment by NavidSassan** [comment]
since we are using our fork of the director with guids, all our baskets have guids. we added the `--without-guids` to the `basket-join` tool, but that only works if you want to import all the baskets, not a single one. we will have to implement a solution for removing guids from single baskets
