### ISSUE TITLE
Icinga: Add new apache service set for Debian 11

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#534]
`apache2.service - UnitFileState is "enabled", but supposed to be "empty"`

**Comment by markuslf** [comment]
On Debian 11, after a standard installation: `systemctl show -p LoadState,ActiveState,SubState,UnitFileState apache2`
```
LoadState=loaded
ActiveState=active
SubState=running
UnitFileState=enabled
```
So no need to add a separate service set (unless I have missed something).
