### ISSUE TITLE
systemd-units-failed: allow wildcards for the --ignore parameter

### ISSUE THREAD

**Issue by MajorTwip** [Linuxfabrik/monitoring-plugins#542]
**Is your feature request related to a problem? Please describe.**
I have a lot of failed services by sshd:

sshd@96-10.0.0.32:22-10.0.0.160:55074.service  ! loaded ! failed ! failed ! SSH Per-Connection Server (10.0.0.160:55074)

Those names are dynamic and therefore im not able to filter them by "--ignore"

**Describe the solution you'd like**
Wildcards for the "--ignore"-argument. 
./systemd-units-failed --ignore=sshd*.service or similar

**Comment by NavidSassan** [comment]
good idea, probably could be done nicely using https://docs.python.org/3/library/fnmatch.html#fnmatch.filter
