### ISSUE TITLE
disk-usage: Critical but first line of plugin output prints "OK"

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#545]
**Describe the bug**
The first line of the plugin output can look OK if the first disk isn't the one with the problem.
This produced questions form Icinga users to the Icinga administrator.

**To Reproduce**
Run the plugin against a host with a C: drive that is OK and a D: drive that is critical.

**Expected behavior**
The disk with the most severe state is in the first line of the plugin output.

**Comment by markuslf** [comment]
That makes perfect sense. This is not a bug, because the plugin itself works, but value display could be more optimal.
