### ISSUE TITLE
icons | not all icons are included 

### ISSUE THREAD

**Issue by sgruber94** [Linuxfabrik/monitoring-plugins#565]
**Describe the bug**

not all the  the icons are included in the icons download.

**To Reproduce**

*  Download icons from readme
https://download.linuxfabrik.ch/monitoring-plugins/assets/icons/icons.tar.gz

**Expected behavior**

A collection of all icons from the checks as download

**Comment by markuslf** [comment]
Thank you for your hint, download is fixed.
