### ISSUE TITLE
docker-info: Raise CRIT on return code != 0

### ISSUE THREAD

**Issue by haytxy** [Linuxfabrik/monitoring-plugins#569]
hello Team,

it seems that when executing "docker-compose down" you will get an UNKNOWN status instead CRITICAL. 
are we able to fix it?

![image](https://user-images.githubusercontent.com/79607995/164327523-e2a0625c-9542-437b-9c73-3f851706bd39.png)
![image](https://user-images.githubusercontent.com/79607995/164328076-a2c4249e-57fe-4ac9-a7f6-77559d0c3389.png)

mj

**Comment by markuslf** [comment]
Thank you, we will fix it.
