### ISSUE TITLE
mysql-stats3: Switch from mysql.connector to PyMySQL

### ISSUE THREAD

**Issue by PointPubMedia** [Linuxfabrik/monitoring-plugins#570]
Hi,

Is it possible to have a new version of the plugin to use the new python module as mysql-connector is no more available in Debian repository.

Maybe you would need to switch to 
**python3-pymysql** - Pure-Python MySQL Driver - Python 3.x

**Comment by markuslf** [comment]
Thanks you for the hint.

**Comment by markuslf** [comment]
There are currently a bunch of new mysql checks on the way (which will replace `mysql-stats3`. We have to adapt them, too.

**Comment by markuslf** [comment]
On RHEL, this is `python3-mysql`.

**Comment by markuslf** [comment]
`mysql-stats` is deprecated and will be removed. Instead, use the bunch of new `mysql-*` plugins in this repository.

Changed the `db_mysql3.py` library from using `mysql.connector` to `pymysql`. Have a look at https://github.com/Linuxfabrik/lib/commit/cbf7a6ad906d7711d448d3b80e622f8c7a0d93b3
