### ISSUE TITLE
needs-restarting3: Debian Buster/bullseye command not found

### ISSUE THREAD

**Issue by PointPubMedia** [Linuxfabrik/monitoring-plugins#572]
The check command doesn't work under Debian using the package needrestart

`OS Error "2 No such file or directory: 'needs-restarting'" calling command "needs-restarting --reboothint"`

**Comment by markuslf** [comment]
`needs-restarting` is only available on Red Hat. We will improve the check so that it also works on Debian-based systems with other methods.

**Comment by markuslf** [comment]
Implemented. Needs updated [libraries](https://github.com/Linuxfabrik/lib), including the new `lib/distro3.py`.
