### ISSUE TITLE
disk-smart3: Some issue detecting disk behind a "DELL" raid card

### ISSUE THREAD

**Issue by PointPubMedia** [Linuxfabrik/monitoring-plugins#579]
Hi,

The plugin is unable to detect drive behind a DELL Raid BUT the smartctl daemon is running perfectly and able to detect as we are receiving email from the smartd daemon!

For example:

```
The following warning/error was logged by the smartd daemon:

Device: /dev/bus/2 [megaraid_disk_03], SMART Failure: DATA CHANNEL IMPENDING FAILURE DATA ERROR RATE TOO HIGH

Device info:
[HP       DG146ABAB4       HPD5], lu id: 0x5000c5000517eb53, S/N: 3NM1QWK600009742E1XH, 146 GB

```

And unable to get data from the boot disk too!

`smartctl failed with exit status "Device open failed, device did not return an IDENTIFY DEVICE structure, or device is in a low-power mode."`

**Comment by markuslf** [comment]
1. What does `lsblk --nodeps --output name,type --noheadings --exclude 9,11,230,252,253,254` returns? Do you see your MegaRAID devices there? Is your boot device listed?
2. What does `smartctl --xall /path/to/your/boot/disk` returns?

**Comment by PointPubMedia** [comment]
The lsblk command return

`sda  disk
sdb  disk
sdc  disk
sdd  disk
sde  disk
sdf  disk
sdg  disk
sdh  disk
sdi  disk
sdj  disk
sdk  disk
sdl  disk
sdm  disk
sdn  disk
sdo  disk
sdp  disk
sdq  disk
sdr  disk
sds  disk
sdt  disk
sdu  disk
sdv  disk
sdw  disk
sdx  disk
sdy  disk
sdz  disk
sdaq disk
sdar disk
sdas disk
sdat disk
sdau disk
sdav disk
sdaw disk
sdax disk
sday disk
sdaz disk
sdba disk
sdbb disk
sdbc disk
sdbd disk
sdbe disk
sdbf disk
sdbg disk
sdbh disk
sdbi disk
sdbj disk
sdbk disk
sdbl disk
sdbm disk
sdbn disk
sdbo disk
sdbp disk
sdbq disk
sdbr disk
sdbs disk
sdbt disk
sdbu disk
sdbv disk
sdbw disk
sdbx disk
sdby disk
sdbz disk
sdca disk
sdcb disk
sdcc disk
sdcd disk
`
The megaraid disk is sdb (that's the LUN itself)
and the smartctl on bootdisk give us

The output of megaclisas-status will give us:

`-- Controller information --
-- ID | H/W Model           | RAM    | Temp | BBU    | Firmware
c0    | PERC 6/i Integrated | 256MB  | N/A  | Good   | FW: 6.3.3.0002

-- Array information --
-- ID | Type   |    Size |  Strpsz | Flags | DskCache |   Status |  OS Path | CacheCade |InProgress
c0u0  | RAID-5 |    953G |   64 KB | RA,WB |  Default |  Optimal | /dev/sdb | None      |None

-- Disk information --
-- ID   | Type | Drive Model                            | Size     | Status          | Speed    | Temp | Slot ID  | LSI ID
c0u0p0  | HDD  | HP DG0146FAMWL HPDC3SD1SY0W            | 136.1 Gb | Online, Spun Up | Unknown  | 28C  | [32:0]   | 0
c0u0p1  | HDD  | HP DG146BB976 HPDC3NM5GL54             | 136.1 Gb | Online, Spun Up | Unknown  | 30C  | [32:1]   | 1
c0u0p2  | HDD  | HP DG146BB976 HPDF3NM8QF0P             | 136.1 Gb | Online, Spun Up | Unknown  | 32C  | [32:2]   | 2
c0u0p3  | HDD  | IBM MBE2147RC 6010D300ST2P601060106010 | 136.1 Gb | Online, Spun Up | Unknown  | 30C  | [32:3]   | 3
c0u0p4  | HDD  | HP DG146BB976 HPDC3NM7T80Z             | 136.1 Gb | Online, Spun Up | Unknown  | 29C  | [32:4]   | 4
c0u0p5  | HDD  | HP DG146ABAB4 HPD73NM3BNDL             | 136.1 Gb | Online, Spun Up | Unknown  | 30C  | [32:5]   | 5
c0u0p6  | HDD  | HP DG0146FAMWL HPDB3SD0RV8T            | 136.1 Gb | Online, Spun Up | Unknown  | 28C  | [32:6]   | 6
c0u0p7  | HDD  | HP DG146BB976 HPDF3NM5A3PR             | 136.1 Gb | Online, Spun Up | Unknown  | 30C  | [32:7]   | 7
`

`smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.3.13-1-pve] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Phison Driven SSDs
Device Model:     KINGSTON SA400S37120G
Serial Number:    50026B7682BD52D8
LU WWN Device Id: 5 0026b7 682bd52d8
Firmware Version: S1Z40102
User Capacity:    120,034,123,776 bytes [120 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
TRIM Command:     Available
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-3 T13/2161-D revision 4
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Tue May  3 09:45:51 2022 EDT
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM feature is:   Disabled
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, frozen [SEC2]
Wt Cache Reorder: Unavailable

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00) Offline data collection activity
                                        was never started.
                                        Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (  120) seconds.
Offline data collection
capabilities:                    (0x11) SMART execute Offline immediate.
                                        No Auto Offline data collection support.
                                        Suspend Offline collection upon new
                                        command.
                                        No Offline surface scan supported.
                                        Self-test supported.
                                        No Conveyance Self-test supported.
                                        No Selective Self-test supported.
SMART capabilities:            (0x0002) Does not save SMART data before
                                        entering power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   2) minutes.
Extended self-test routine
recommended polling time:        (  10) minutes.

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     -O--CK   100   100   000    -    100
  9 Power_On_Hours          -O--CK   100   100   000    -    20971
 12 Power_Cycle_Count       -O--CK   100   100   000    -    6
148 Unknown_Attribute       ------   100   100   000    -    0
149 Unknown_Attribute       ------   100   100   000    -    0
167 Write_Protect_Mode      ------   100   100   000    -    0
168 SATA_Phy_Error_Count    -O--C-   100   100   000    -    0
169 Bad_Block_Rate          ------   100   100   000    -    0
170 Bad_Blk_Ct_Erl/Lat      ------   100   100   010    -    0/0
172 Erase_Fail_Count        -O--CK   100   100   000    -    0
173 MaxAvgErase_Ct          ------   100   100   000    -    0
181 Program_Fail_Count      -O--CK   100   100   000    -    0
182 Erase_Fail_Count        ------   100   100   000    -    0
187 Reported_Uncorrect      -O--CK   100   100   000    -    0
192 Unsafe_Shutdown_Count   -O--C-   100   100   000    -    5
194 Temperature_Celsius     -O---K   034   054   000    -    34 (Min/Max 28/54)
196 Reallocated_Event_Count -O--CK   100   100   000    -    0
199 SATA_CRC_Error_Count    -O--CK   100   100   000    -    0
218 CRC_Error_Count         -O--CK   100   100   000    -    0
231 SSD_Life_Left           ------   088   088   000    -    88
233 Flash_Writes_GiB        -O--CK   100   100   000    -    4429
241 Lifetime_Writes_GiB     -O--CK   100   100   000    -    4594
242 Lifetime_Reads_GiB      -O--CK   100   100   000    -    2831
244 Average_Erase_Count     ------   100   100   000    -    129
245 Max_Erase_Count         ------   100   100   000    -    174
246 Total_Erase_Count       ------   100   100   000    -    55399
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x01           SL  R/O      1  Summary SMART error log
0x02           SL  R/O      1  Comprehensive SMART error log
0x03       GPL     R/O      1  Ext. Comprehensive SMART error log
0x04       GPL,SL  R/O      8  Device Statistics log
0x06           SL  R/O      1  SMART self-test log
0x07       GPL     R/O      1  Extended self-test log
0x10       GPL     R/O      1  NCQ Command Error log
0x11       GPL     R/O      1  SATA Phy Event Counters log
0x30       GPL,SL  R/O      9  IDENTIFY DEVICE data log
0x80-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xde       GPL     VS       8  Device vendor specific log

SMART Extended Comprehensive Error Log Version: 1 (1 sectors)
No Errors Logged

SMART Extended Self-test Log Version: 1 (1 sectors)
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

Selective Self-tests/Logging not supported

SCT Commands not supported

Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
0x01  0x008  4               6  ---  Lifetime Power-On Resets
0x01  0x010  4           20971  ---  Power-on Hours
0x01  0x018  6      1045693856  ---  Logical Sectors Written
0x01  0x020  6       180365214  ---  Number of Write Commands
0x01  0x028  6      1642906725  ---  Logical Sectors Read
0x01  0x030  6        28256879  ---  Number of Read Commands
0x07  =====  =               =  ===  == Solid State Device Statistics (rev 1) ==
0x07  0x008  1              14  ---  Percentage Used Endurance Indicator
                                |||_ C monitored condition met
                                ||__ D supports DSN
                                |___ N normalized value

Pending Defects log (GP Log 0x0c) not supported

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  4            0  Command failed due to ICRC error
0x0002  4            0  R_ERR response for data FIS
0x0005  4            2  R_ERR response for non-data FIS
0x000a  4            6  Device-to-host register FISes sent due to a COMRESET
`

**Comment by markuslf** [comment]
Do you run the check plugin with root privileges? Try running it under the root account, or, if configured, try `sudo /path/to/disk-smart3`.

What does `disk-smart3` return in case of the MegaRAID controller?

**Comment by markuslf** [comment]
How does your `/etc/smartmontools/smartd.conf` look like?

**Comment by PointPubMedia** [comment]
The smartd.conf file is the default one with nothing in it except 

DEVICESCAN -d removable -n standby -m root -M exec /usr/share/smartmontools/smartd-runner

**Comment by markuslf** [comment]
If the problem still exists, a remote session might help clarifying some things. Drop us a note at our info mail address on how to get in contact. Closing this for now as we can't help in this special case.
