### ISSUE TITLE
sensors-fan3: Requirement for DELL Servers

### ISSUE THREAD

**Issue by PointPubMedia** [Linuxfabrik/monitoring-plugins#580]
Not sure if it's a bug, but, what is the requirement for the FAN detection in DELL servers ?

**Comment by markuslf** [comment]
Please use [Discussions](https://github.com/Linuxfabrik/monitoring-plugins/discussions) for this type of questions.

You need the `psutil` Python library as stated in [the plugin README](https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/sensors-fans). Access to `/sys/class/hwmon/hwmon*/fan*_*` or `/sys/class/hwmon/hwmon*/device/fan*_*` is also required.
