### ISSUE TITLE
docker-stats: Improve handling of container names

### ISSUE THREAD

**Issue by Gninieb** [Linuxfabrik/monitoring-plugins#586]
**Is your feature request related to a problem? Please describe.**
We are using Docker Swarm and so we get something like "traefik_traefik.2.1idw12p2yqpxutlzkcwign4at" as NAME in docker stats.
This was composed as follows: "<name of container>.<replica number>.<dynamic ID>".
The dynamic ID changes every time the container is restarted and is a problem in connection with valid perfdata e.g. regarding whisper entries in metrics. 

**Describe the solution you'd like**
A shortening of the name after the replica number would be very helpful! This could be triggerd through a argument like -s for SWARM Mode

**Describe alternatives you've considered**
Alternatively, you could generally shorten the name before the second point and save the optional argument

**Additional context**
-

**Comment by markuslf** [comment]
Sounds reasonable, we'll take a look at it.

**Comment by Gninieb** [comment]
Hey, thank you for the improvement! But I think you missed the shortening in at perfdata output?

**Comment by markuslf** [comment]
Handled in https://github.com/Linuxfabrik/monitoring-plugins/issues/600
