### ISSUE TITLE
file-count: Unknown NtStatus error returned 'STATUS_PATH_NOT_COVERED'" while opening or reading \\server\path

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/monitoring-plugins#588]
**Describe the bug**

`'/usr/lib64/nagios/plugins/file-count' '--always-ok' '--password' 'PW' '--pattern' '*' '--timeout' '3' '--url' 'smb://\\server\path' '--username' 'USER'`

returns

`I/O error "Unknown NtStatus error returned 'STATUS_PATH_NOT_COVERED'" while opening or reading smb://\\server\path`

**Comment by slalomsk8er** [comment]
Had no chance to work before https://github.com/jborean93/smbprotocol/pull/49 works with current version but still a problem with &uuml; etc. in DFS Path.

**Comment by markuslf** [comment]
So do you mean that
* a filename containing `ü` is returned as `&uuml;` and therefore not counted correctly
* or that a filename containing `&uuml;` is not counted correctly?

**Comment by slalomsk8er** [comment]
`ü` in the smb:// path results in a error and `&uuml;` "works" without error but results always in a count of 0.

**Comment by markuslf** [comment]
And `ü` results in above mentioned "STATUS_PATH_NOT_COVERED"?

**Comment by slalomsk8er** [comment]
> And `ü` results in above mentioned "STATUS_PATH_NOT_COVERED"?

If I remember correctly that error was because auf the old lib. The unencoded `ü` resultet ins a error with ansi/ascii something.

**Comment by markuslf** [comment]
Tested, and can not reproduce with the current libs and plugins. Connecting to an smb share with umlauts in the share name works, and the count is correct. Closing this issue.
