### ISSUE TITLE
GitHub Action for Nuitka produces a monitoring-plugins.zip.zip

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/monitoring-plugins#593]
**Describe the bug**
After downloading, if you extract `monitoring-plugins.zip.zip`, you get a `monitoring-plugins.zip` which you have to extract again. The Action should simply create a `monitoring-plugins.zip` containing the plugins if possible.

**Comment by NavidSassan** [comment]
makes sense - all artifacts are automatically zipped by github, so we don't need to manually do that in the workflow. i will adjust it

**Comment by NavidSassan** [comment]
groesse wird im webgui zwar falsch angezeigt, nach dem runterladen stimmt es aber

**Comment by markuslf** [comment]
Still produces a monitoring-plugins.zip.zip (shown in Webinterface as monitoring-plugins.zip, but downloaded as monitoring-plugins.zip.zip)
