### ISSUE TITLE
docker-stats: missing shortening of containername in perfdata output

### ISSUE THREAD

**Issue by Gninieb** [Linuxfabrik/monitoring-plugins#600]
Hey, thank you for the improvement! But I think you missed the shortening at the perfdata output?

_Originally posted by @Gninieb in https://github.com/Linuxfabrik/monitoring-plugins/issues/586#issuecomment-1186980561_

**Comment by markuslf** [comment]
Oh, yes, you are right. I currently also see some inconsistences for docker-stats compared to docker-info, plus a problem if using podman on RHEL 8. Will be fixed later.

**Comment by markuslf** [comment]
Fixed. As a side-effect the check now also works with Podman.
