### ISSUE TITLE
Legacy commands definitions

### ISSUE THREAD

**Issue by mmartinello** [Linuxfabrik/monitoring-plugins#601]
### Is your feature request related to a problem? Please describe.

I am wondering if commands definitions for legacy Icinga configuration would be provided.
This is because even if I know that everyone are using Icinga Director right now, I'm actually generating Icinga configuration using Ansible, and for this reason I need the legacy commands definitions to use Linuxfabrik Plugins.

Thank you!

### Describe the solution you'd like

Write the command definitions in a unique file for all check commands or in a single file for each check command.
This would be imported into `/etc/icinga2/conf.d` directory.

**Comment by markuslf** [comment]
That's a good point that we need to discuss. If we decide to do this (can't promise), it will take a while to get it available.

If you already have some definitions, a pull request would be appreciated.

**Comment by NavidSassan** [comment]
Alternatively you can use the icinga director itself to generate the configuration, and use those for ansible. For that, import the basket in the director, deploy all the changes and go to deployments > choose the latest one > and then click the config tab at the top.

**Comment by fabbricalox** [comment]
Or do it like @NavidSassan says (import, deploy) and then do a simple "icingacli director command show fu" or write a small script which iterates over the command names and calls the icingacli.

**Comment by markuslf** [comment]
Closed as there is a workaround.
