### ISSUE TITLE
check_service should be able to check multiple windows services at once

### ISSUE THREAD

**Issue by rtritscher** [Linuxfabrik/monitoring-plugins#609]
### Is your feature request related to a problem? Please describe.

I'm checking multiple windows-services on a host with almost the same name - they just differ by a serial number. Currently, each windows-service needs its own check.

### Describe the solution you'd like

--service accepts also regular expressions

two new arguments:
--warning, --critical,  accepting ranges: e.g. at least 10 but not more than 20 Windows-Services must meet --status

**Comment by markuslf** [comment]
Something like that?

`service.exe --service="^win.*" --status=running --warning=5:`

```
4 services named "^win.*" with status "running" found, but expected "5:" [WARNING].

Service Name        ! Status  ! Startup
--------------------+---------+-----------
WinDefend           ! running ! automatic
WinHttpAutoProxySvc ! running ! manual
Winmgmt             ! running ! automatic
WinRM               ! running ! automatic
```

**Comment by rtritscher** [comment]
Yes exactly. :-)
