### ISSUE TITLE
Grafana panel: Disk usage: Warning and critical threshold mixed up

### ISSUE THREAD

**Issue by bzblf** [Linuxfabrik/monitoring-plugins#611]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Relates to the grafana panel in disk-usage check
The threshold for percent warning and critical (also the color) are mixed-up.

### Steps to reproduce - Plugin call

```shell
The problem relates not the check itself
Look in Icinga and klick the `-percent warn` or `-percent crit` below the graph. You can see that the threshold is mixed up.
```

### Steps to reproduce - Plugin Version

The problem relates not to the check itself

### Steps to reproduce - Data

No explicit data needed. Look at the threshold warning and critical

### Environment

Doesn't relate to a specific OS

### Additional info

It is a general Issue that belongs the grafana Panel

**Comment by markuslf** [comment]
Dashboard rebuilt from scratch.
