### ISSUE TITLE
basket import fails with Unable to load object referenced from host "tpl-host-generic"

### ISSUE THREAD

**Issue by fireba11** [Linuxfabrik/monitoring-plugins#612]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Importing the basket into director fails.

Full output:
ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php:567 with message: Unable to load object referenced from host "tpl-host-generic", failed to load icinga_zone "master"

(Trying to import via icingacli due to size.)

### Steps to reproduce - Plugin call

```shell
Importing the basket into director fails so ... ;-)
```

### Steps to reproduce - Plugin Version

2022072001

### Environment

Director version (System - About): 1.9.1
Icinga 2 version (icinga2 --version): 2.13.2-1

**Comment by NavidSassan** [comment]
Do you have a `master` zone defined in the Icinga Director > Icinga Infrastructure > Zones (https://example.com/icingaweb2/director/zones)?

**Comment by fireba11** [comment]
nope

**Comment by NavidSassan** [comment]
during the `icinga2 node wizard` of the icinga2 master you needed to provide a `Master zone name`. If you did not name your master zone `master` during the initial `icinga2 node wizard`, then search and replace `"zone": "master"` with `"zone": "your-master-zone-name"` in the `icingaweb2-module-director-basket.json`.
