### ISSUE TITLE
file-age: critical reported for new files because modification time is negative or not set

### ISSUE THREAD

**Issue by mdicss** [Linuxfabrik/monitoring-plugins#618]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Bug description

On linux, the check produces sometimes not expected results with newly created files and default settings for --critical. The problem seems to be the starting range which is 0 and the returned file modification time.
Problem occurs with python 2 and 3.

### Steps to reproduce - Plugin call

```shell
# touch /tmp/test; stat /tmp/test; ./file-age --timeout 30 --filename=/tmp/test --only-files --warning=@21000:
  File: ‘/tmp/test’
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 27h/39d Inode: 2539252984  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-10-10 12:23:13.318786972 +0200
Modify: 2022-10-10 12:23:13.318786972 +0200
Change: 2022-10-10 12:23:13.318786972 +0200
 Birth: -
0 items outside count range "0" and outside "@21000:" time range. 1 item outside count range "0" and outside "1Y" time range. 1 item checked.

* /tmp/test: -1Y 12M [CRITICAL]
```

### Steps to reproduce - Plugin Version

v2022071901

### Python version

Python 3

### Environment

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Same results with:
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"

**Comment by markuslf** [comment]
At first glance the same behaviour on Fedora 36.

**Comment by markuslf** [comment]
Fixed. BTW, in your case `--timeout 30` is not necessary because you are not retrieving from a URL.
