### ISSUE TITLE
network-io: Reinstate this check

### ISSUE THREAD

**Issue by henkf** [Linuxfabrik/monitoring-plugins#619]
Hi Linuxfabrik, can you tell us if you already have plans to reinstate the network-io check?

From Changelog 2020041501

> Removed
> 
> Monitoring Plugins:
> 
>     docker-info, docker-container, network-io, redis, xca-cert for now. We will rewrite them from scratch soon.

**Comment by markuslf** [comment]
Yes, definitely.

**Comment by markuslf** [comment]
Done.

**Comment by henkf** [comment]
Great! Will try this as soon as possible.
