### ISSUE TITLE
network-connections: Alert if there's more than a specified number of conns

### ISSUE THREAD

**Issue by Freeaqingme** [Linuxfabrik/monitoring-plugins#621]
### Is your feature request related to a problem? Please describe.

I have an application that leaks TCP connections:
```
/usr/lib64/nagios/plugins/network-connections       
tcp6 ESTABLISHED: 37732, tcp ESTABLISHED: 6, tcp TIME WAIT: 5, udp6 NONE: 5, udp NONE: 4, tcp6 LISTEN: 4, tcp LISTEN: 4|'tcp6_ESTABLISHED'=37732;;;; 'tcp_ESTABLISHED'=6;;;; 'tcp_TIME_WAIT'=5;;;; 'udp6_NONE'=5;;;; 'udp_NONE'=4;;;; 'tcp6_LISTEN'=4;;;; 'tcp_LISTEN'=4;;;;
```

Obviously the application needs fixing (and it will be! :)). These connections are all to the same host, and when there's no more free ports, this will lead to a DoS.

### Describe the solution you'd like

Monitoring wise it would be nice to be able to get an alert if this host has 'too many' active connections. 

On [this page](https://docs.linuxfabrik.ch/monitoring-plugins/network-connections.html) it says:
> Does not WARN or CRIT on anything, because we currently do not know on what. Until there is some clarification (you could [submit an issue](https://github.com/Linuxfabrik/monitoring-plugins/issues//new)), this check is useful for debugging purposes.

Well, here's the issue :)

I realize it is difficult, if not impossible, to have a predefined number of connections that's problematic, it would be different per host. However, maybe we could make it so that the user is able to specify what thresholds they'd like to have?

In this particular case, I would expect this host to never have more than a few, maybe a hundred, tcp connections. So I could configure a treshold of warn at 500, critical at 2500.  

### Additional context

Thank you for this awesome project!

**Comment by markuslf** [comment]
Sounds reasonable, so would something like `--warn-tcp6-established`, `--warn-tcp-established`, `--tcp-time-wait` etc. make sense, where all default to `None`?

**Comment by Freeaqingme** [comment]
That would work. I figured I wouldn't make a proposal myself to leave the options open. If we wanted to be able to set the thresholds individually, maybe we should also do the same for UDP? While we're on it, we _could_ add a threshold for the listen numbers as well. If you have a server that typically only has a dozen active listen sockets, and it suddenly increases to a couple of hundred, chances are some app has gone haywire, or your system was hacked.

Having said that, for my particular use case I would also be totally happy with just two arguments in total:  ```--warn-tcp46-established, --crit-tcp46-established``` that would simply alert on the total number of tcp connections. Or maybe even: for both TCP and UDP.

However, I suppose it's only a matter of time before someone has a use case where it would be necessary to be able to configure all thresholds individually.

**Comment by markuslf** [comment]
Have a look at the README for details.

**Comment by Freeaqingme** [comment]
@markuslf awesome! From the README it looks very reasonable and easy to work with.
