### ISSUE TITLE
redis-status: Add option to disable hit-ratio check

### ISSUE THREAD

**Issue by daniel-tihanyi** [Linuxfabrik/monitoring-plugins#623]
### Is your feature request related to a problem? Please describe.

Hello,
it would be in beneficial if it would be possible to disable individual parameters in the redis-status check. For example if hit-ratio is not a concern, a flag like "--ignorehitratio" would be nice.

### Describe the solution you'd like

Flags like "--ignorehitratio" or --"ignorehugepages" and others if the given parameter is considered a non-issue by the user.

### Additional context

In not all cases is it possible or allowed to change for example kernel parameters like transparent_hugepage. In this case, if the affects of this is accepted, would be nice if this part of the check could be ignored.

**Comment by markuslf** [comment]
Good point.

**Comment by asltbbg** [comment]
It wold be nice if you add aswitch like 

--tollerated-part-sync <integer>

beacause if you have an asyncron replication a smal amount of "denied partial resync requests" is normal

**Comment by markuslf** [comment]
Implemented a bunch of such switches:
* `--ignore-maxmemory0`
* `--ignore-overcommit`
* `--ignore-somaxconn`
* `--ignore-sync-partial-err`
* `--ignore-thp`
