### ISSUE TITLE
Feature request: NTP check for Windows

### ISSUE THREAD

**Issue by michaje-gsc** [Linuxfabrik/monitoring-plugins#629]
### Is your feature request related to a problem? Please describe.

We have to use different plugins, one per platform, to check NTP.  We would enjoy a Python plugin that could be used on any underlying platform: Linux, Windows, or even others...

### Describe the solution you'd like

The check we want to achieve is just making sure the server is synchronised with a given NTP server, with the stratum level being returned - critical if 0, warning if above a certain provided number.

**Comment by markuslf** [comment]
We splitted the checks from one generic ntp check into three different ones, because it became too complicated to unifiy ntpd, chronyd and systemd-timesyncd because of their very different behaviour and results. So we will stay with that.

But yes, a check for NTP on Windows is currently missing. What is the command to get NTP insights on Windows?

**Comment by michaje-gsc** [comment]
Thank you for replying!
Here follows the Windows prompt command, but what I wish to have is a single plugin that we could invoke from Icinga regardless of the platform.  The implementation of the plugin would assess the platform and choose the correct implementation (Unix flavour, Windows flavour, etc.), and return a standard output, including the stratum level.
Kind regards,
Jean

C:\Users\me>**w32tm /query /status**
_Leap Indicator: 0(no warning)
Stratum: 6 (secondary reference - syncd by (S)NTP)
Precision: -23 (119.209ns per tick)
Root Delay: 0.0076020s
Root Dispersion: 0.0875065s
ReferenceId: 0x0A5F0108 (source IP:  10.1.2.3)
Last Successful Sync Time: 25/11/2022 15:53:52
Source: MyServer
Poll Interval: 10 (1024s)_


C:\Users\me>
