### ISSUE TITLE
veeam-status: Add an option switch to "WarningVmLatestState" for an integer value of tolerated VM warnings

### ISSUE THREAD

**Issue by asltbbg** [Linuxfabrik/monitoring-plugins#630]
### Is your feature request related to a problem? Please describe.

We have 2 blackbox appliance VM that always quit the backupjob with an warning. But the backup is without anny issuses.

The warnige by this Icinga plugin is with evry check. We don't wan to use the --always ok switch because we dont see other issues in the monitoring.

I have changed :
"
  val = result['overview']['WarningVmLastestStates']
    if val > 2:
"
in the code.

So the check runs perfect:-) 

It would be nice when there would be a switch like "--ignore_VM_WARNINGS_count" or similar.

Thank you

### Describe the solution you'd like

"--ignore_VM_WARNINGS_count" or similar name.

### Alternatives

i have to hack the code by my self evry update ...

**Comment by markuslf** [comment]
Makes sense if these values additionally become configurable:
* FailedVmLastestStates (default: 0)
* WarningVmLastestStates (default: 0)
* FailedJobRuns (default: 0)
* WarningsJobRuns (default: 0)
* MaxBackupJobDuration (default: 86400)
* MaxReplicaJobDuration (default: 86400)
