### ISSUE TITLE
updates: On Windows with closed firewall a PowerShell error is returned

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#633]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Bug description

see title

### Steps to reproduce - Plugin call

```shell
'C:\ProgramData\icinga2\usr\lib64\nagios\plugins\updates.exe' '--critical' '50' '--warning' '2'
```

### Steps to reproduce - Plugin Version

v2022021501

### Steps to reproduce - Data

```
Exception from HRESULT: 0x80072EE2
At line:4 char:5
+     $Pending = $SearchIndex.Search('IsInstalled=0');
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
```

### Environment

Windows

**Comment by markuslf** [comment]
"Closed Firewall" means "Block all outgoing connections".

Confirmed. Only happens in Powershell after a 10 second timeout. In a batch terminal, updates.exe hangs forever.

**Comment by markuslf** [comment]
Fixed in source. If you like, please give it a try. Don't forget to [use the updated libs](https://github.com/Linuxfabrik/lib) as well (implemented a new timeout parameter in `shell_exec()` - it is more general than relying on PowerShell).
