### ISSUE TITLE
nextcloud-security-scan (for example): CERTIFICATE_VERIFY_FAILED - even on official signed certificates

### ISSUE THREAD

**Issue by marcelfischer** [Linuxfabrik/monitoring-plugins#634]
Hi,
using nextcloud-security-scan and other plugins, I see "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate".
On self signed I could accept that. But I even get it von scan.nextcloud.com
Is that a bug? Im using linuxfabrik-monitoring-plugins-2022072001

Is there a way to fix that? Does python not using the ca certs of debian? Can I disable the ssl verify for self signed certs?

**Comment by markuslf** [comment]
I don't think this is a problem with the plugins. What does this Python code returns on the affected machine?

```
#! /usr/bin/env python3

import urllib.request

url = 'https://ipecho.net/plain'
request = urllib.request.Request(url)
response = urllib.request.urlopen(request)

print(response.read())
print(response.getcode())
```

BTW, it would be easier for us if you use our GitHub issue templates.

**Comment by marcelfischer** [comment]
This works:
```
# python3 test.py
b'217.86.186.109'
200
```

Sorry github skipped that somehow

**Comment by markuslf** [comment]
We need at least:

Steps to reproduce - Plugin call
Your plugin command line call (plugin-name --param1=value1 --param2=value2).
Example: `/usr/lib64/nagios/plugins/cpu-usage --count 5 --critical 90 --warning 80`


Steps to reproduce - Data
Enter here the output of your operating system or application (which will be analyzed by the plugin as input), e.g. JSON data, the output of the shell comand that the plugin calls etc.



Environment
Please give us as much information as possible about your system. For example, the output of uname -a.

**Comment by marcelfischer** [comment]
Plugin call:
# '/usr/lib64/nagios/plugins/nextcloud-security-scan' '--timeout' '7' '--trigger' '14' '--url' 'cloud.naturladen-braunschweig.de'
Output:
URL error "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)" for https://scan.nextcloud.com/api/queue

# '/usr/lib64/nagios/plugins/nextcloud-security-scan' -V
nextcloud-security-scan: v2022021501 by Linuxfabrik GmbH, Zurich/Switzerland
# file '/usr/lib64/nagios/plugins/nextcloud-security-scan'
/usr/lib64/nagios/plugins/nextcloud-security-scan: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9230f3fa19123436d7e9b46b02c11f1e492895c1, for GNU/Linux 2.6.32, stripped

root@cloud:~# uname -a
Linux cloud 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

root@cloud:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Im not really sure whats going on.
Other programs like curl are working:
root@cloud:~# curl https://scan.nextcloud.com/api/queue
"Forbidden"

I cannot really tell you much more about the environment. Its plain debian

**Comment by markuslf** [comment]
The message `unable to get local issuer certificate` means that Python cannot find the needed issuer certificates (CA certificate) on your local system.

I tested on a fresh Debian 11 Vagrant machine (and some others) and can't reproduce the issue. On my side your call is working fine. Maybe this is a configuration issue.

**Comment by marcelfischer** [comment]
And you used the current deb package from the repo? Just tested on another customer, same problem on Debian but no issue on CentOS

**Comment by markuslf** [comment]
This is a very important peace of information. ;-)

Sorry, no, I tested with the source variant first. After your information update I can confirm the error with the compiled / packed variant, same behaviour on my Debian 11 VM. Only the compiled version is affected, btw. Using the python source code variant works. Thank your for reporting this.

**Comment by markuslf** [comment]
Will be fixed with the new upcoming installation packages (tests were successful, so closing this).

**Comment by Cyberes** [comment]
Waiting on that new release for this and the systemd...
