### ISSUE TITLE
systemd-unit: "Bash command failed" on Debian 11 (systemd 247)

### ISSUE THREAD

**Issue by bangerer** [Linuxfabrik/monitoring-plugins#635]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Bug description

Hello everyone. :)

Executing the `systemd-unit` Plugin on Debian 11 (using any unit file present on the system) produces the error *Bash command failed -- no version information available*:

```bash
root@deb11server:~# /usr/lib64/nagios/plugins/systemd-unit --unit=ssh.service
Bash command `systemctl show -p LoadState,ActiveState,SubState,UnitFileState ` failed.
Stdout: LoadState=loaded
ActiveState=active
SubState=running
UnitFileState=enabled

Stderr: systemctl: /usr/lib64/nagios/plugins/libselinux.so.1: no version information available (required by systemctl)
```

The plugin output causes an *UNKNOWN* state for those services in Icinga2 using the "systemd-unit"-Plugin as a Check Command.

However, the same command runs fine in Debian 10 (systemd 241) or Ubuntu 20.04 (systemd 245), all other things being equal:

```bash
root@ubu2004server:~# /usr/lib64/nagios/plugins/systemd-unit --unit=ssh.service
ssh.service is loaded, active, running
```

(Using "root" only to demonstrate; it's the same with any other Linux user, including the default "nagios" User for this usecase.)

Hope this covers it. Glad to help ask any follow-up questions anytime.
Thanks for your awesome work & have a good day,

\Barney

### Steps to reproduce - Plugin call

```shell
# spin up a Debian 11 machine
# install package "linuxfabrik-monitoring-plugins" from official repo


# check what units are are available on the system
systemctl list-units

# dry-run with pure systemd
systemctl show -p LoadState,ActiveState,SubState,UnitFileState ssh.service


# plugin call -- barebones
/usr/lib64/nagios/plugins/systemd-unit --unit=ssh.service

# plugin call -- with some parameters
'/usr/lib64/nagios/plugins/systemd-unit' '--activestate' 'active' '--loadstate' 'loaded' '--severity' 'crit' '--substate' 'running' '--unit' 'ssh.service' '--unitfilestate' 'enabled'

# plugin call -- for the apache2 service (if present on the system)
'/usr/lib64/nagios/plugins/systemd-unit' '--activestate' 'active' '--loadstate' 'loaded' '--severity' 'crit' '--substate' 'running' '--unit' 'apache2.service' '--unitfilestate' 'enabled'
```

### Steps to reproduce - Plugin Version

```bash
root@deb11server:~# /usr/lib64/nagios/plugins/systemd-unit --version
systemd-unit: v2022021501 by Linuxfabrik GmbH, Zurich/Switzerland
```

Source: Package linuxfabrik-monitoring-plugins, Version 2022072001
`deb https://repo.linuxfabrik.ch/monitoring-plugins/debian/  bullseye-release main`

### Python version

Python 3

### Environment

```bash
root@deb11server:~# python3 --version
Python 3.9.2

root@deb11server:~# uname -a
Linux deb11server 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

root@deb11server:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@deb11server:~# systemctl --version
systemd 247 (247.3-7+deb11u1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by markuslf** [comment]
Confirmed, same behaviour on my test VM. Thank your for reporting this.

**Comment by markuslf** [comment]
Only the compiled version is affected, btw. Using the python source code variant works.

**Comment by markuslf** [comment]
Will be fixed with the new upcoming installation packages (tests were successful, so closing this).
