### ISSUE TITLE
about-me3: Add Maker and Model

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#637]
### Is your feature request related to a problem? Please describe.

I wanted to quickly check the model of a raspberry pi and could not via the "About me" service.

### Describe the solution you'd like

The command `cat /sys/firmware/devicetree/base/model` provides

> Raspberry Pi 3 Model B Plus Rev 1.3

and could be incorporated into the `about-me` output.

On PC there exists the command `# dmidecode | grep -A3 '^System Information`, for which I get:

> System Information
>         Manufacturer: Hewlett-Packard
>         Product Name: HP EliteDesk 800 G1 SFF
>         Version: Not Specified

Not sure if there exists an abstraction that would provide the information for all Linux devices and not just for raspberry pi.

**Comment by markuslf** [comment]
Please try.
