### ISSUE TITLE
notify-host-mail3: Generate URL for icingadb plugin also

### ISSUE THREAD

**Issue by soulsymphonies** [Linuxfabrik/monitoring-plugins#643]
### Is your feature request related to a problem? Please describe.

The `notify-host-mail` notification plugin returns an URL to the host in icingaweb2, this works perfectly for the old "monitoring" plugin that uses the Icinga IDO, but not for the new "icingadb" plugin, because the URL is different there.

The same would probably apply to the other notification plugins as well, when they generate the URLs for Icingaweb2, so probably all of them, I have not yet tested them.

### Describe the solution you'd like

I'm actually not a python programmer, that's why I didn't create a pull request.

I managed to change the code to get the right URL for icingadb out of it, I attached the snippet of the part that I changed, below.

This obviously would remove the support for the old icingaweb2 monitoring plugin, which might work for me but not for others, maybe a parameter could be implented in the notification plugin, so it can be indicated if icingadb or the monitoring plugin is used in Icinga2 Web and then generate the appropriate URL.

The actual URL for Icingadb is `[icingaweb2-url]/icingadb/hosts#!/icingadb/host?name=[hostname]`

Here is the code snippet, that generates the URL for icingadb:
```
if args.ICINGAWEB2_URL and args.HOSTNAME and args.HOSTNAME:
        params = urllib.parse.urlencode({
            'host': args.HOSTNAME,
        }, quote_via=urllib.parse.quote)
        rows += [
            {
                'left_column': 'IcingaWeb2 URL:',
                'right_column': urllib.parse.urljoin('{}/'.format(args.ICINGAWEB2_URL), 'icingadb/hosts#!/icingadb/host?name={}'.format(args.HOSTNAME))
            },
        ]
```

**Comment by NavidSassan** [comment]
Thanks for the input, definitely makes sense to support IcingaDB links too :)  We will have to consider what the best way is to how to support both the old IcingaWeb2 monitoring module and IcingaDB
