### ISSUE TITLE
about-me: Make external IP search configurable with 3rd party providers (and disabled by default)

### ISSUE THREAD

**Issue by xeiss** [Linuxfabrik/monitoring-plugins#645]
### Is your feature request related to a problem? Please describe.

I tried the about-me3 plugin and find out, does it always make a HTTP Connection to "ipinfo.io", "ipecho.net" and "ipv4.icanhazip.com" which all are services in the USA.
It only does this to show the "external ip" which isn't possible for the most our servers, because we only allow few internet services.

Alone through privacy policy I can't use the whole plugin because of that, but I'm also worried about the third-party terms of use.

### Describe the solution you'd like

Make an "-no-external-lookup" argument, which I can add to disable this behavior.

Or disable this behavior per default, which may be the better privacy decsion. And with an option "-external-lookup-url http://ipv4.icanhazip.com/", everyone could also be use his own Webserver/CDN to get external IPs from some of his devices.

### Additional context

Tested on Debian and Redhat with release 2022072001 and sudo privileges.

**Comment by markuslf** [comment]
Good point, I will implement the latter.

**Comment by markuslf** [comment]
Fixed in source. If you like, please give it a try. Don't forget to [use the updated the libs](https://github.com/Linuxfabrik/lfops) as well.

**Comment by xeiss** [comment]
Nice, thank you for the really fast update!
I testet the new version on some of my test maschines. Works flawless with/without internet, also with "--public-ip-url", which i tested with my CDN. 
But the best part, no internet access per default, that is a good decision.

**Comment by markuslf** [comment]
Thank you for the valuable input. :-)
