### ISSUE TITLE
pip-updates: Include- and exclude-property 

### ISSUE THREAD

**Issue by dorkmaneuver** [Linuxfabrik/monitoring-plugins#646]
### Is your feature request related to a problem? Please describe.

I am using graphite-web installed by pip. I monitor the virtual environment with your nice plugin. However, graphite-web depends on Django  3.0.14 and django-tagging 0.4., so I have to keep them on this version until graphite-web is updated. 

### Describe the solution you'd like

I could set warning/critical to "3" to not have a warning. But more elegant approach could be, to give it an include- and an exclude-property. Then I could ignore these packages, wait for others to update and if I see that graphite-web has an update, update these a well to their last supported version. This feature would be a bit more precise in the check. :)

**Comment by markuslf** [comment]
Sounds reasonable. On which operating system do you use the plugin? Which Python and Pip version?

**Comment by dorkmaneuver** [comment]
Thanks! And sorry - it's a Debian 10, Python 3.7.3 and pip 23.0. :)

**Comment by markuslf** [comment]
I implemented a bunch of new parameters that allow you to control pip's update determination more precisely. `--exclude` is one of the most interesting for you, I guess. Greetings to Berlin - will we see each other at the [next Icinga Camp 2023](http://mailings.icinga.com/m/14234893/1120422-be9b4165c38dd25ea677c4eb30274269bd23311f7554322e3445b85291cfa91dc97d437090f878c80baac3a046f2846f)?

**Comment by dorkmaneuver** [comment]
Wow, Markus, great! I'm deeply impressed! Huge thanks and best wishes back to Zürich and yes, looking forward to see you at Icinga Camp 2023! Have a beautiful weekend!

**Comment by dorkmaneuver** [comment]
Just a short follow up: I got a "/bin/sh: 1: source: not found" as output. When I changed line 204 of the script and replaced "source" with a "."
`cmd = '. {} && {}'.format(args.VIRTUALENV, cmd)`
it worked as expected. Thanks for this excellent plugin!

**Comment by markuslf** [comment]
Changed it in https://github.com/Linuxfabrik/monitoring-plugins/commit/26a697cf96c803ab225ae6f08defbbbb2424fa59, thank you. :-)
