### ISSUE TITLE
kemp-services3: Credentials not converted correctly

### ISSUE THREAD

**Issue by asltbbg** [Linuxfabrik/monitoring-plugins#653]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] Compiled, from repo
- [X] Source Code, from GitHub

### Bug description

The Plugin isn't working the error is:

Traceback (most recent call last):
  File "/usr/local/lib/LinuxFabric/check-plugins/kemp-services/./kemp-services3", line 199, in 'module'
    main()
  File "/usr/local/lib/LinuxFabric/check-plugins/kemp-services/./kemp-services3", line 152, in main
    base64.b64encode(args.USERNAME + ':' + args.PASSWORD)
  File "/usr/lib/python3.9/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

if I change 

base64.b64encode(args.USERNAME + ':' + args.PASSWORD)

to

base64.b64encode(bytes(args.USERNAME + ':' + args.PASSWORD, encoding='ascii'))

I get the error

HTTP error "401 Unauthorized" while fetching https://********:443/access/listvs

but my credentials are correct

### Steps to reproduce - Plugin call

 ./kemp-services -H *** --username *** --password *** --insecure

### Environment

Linux ***  5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

Kemp:

Vers:7.2.57.0.21570.RELEASE (VMware)

### Plugin Version

kemp-services3: v2023021701 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

Python 3.9.2

**Comment by markuslf** [comment]
Can you give it a try?
