### ISSUE TITLE
kemp-services: Display the original status of every Virtual Service

### ISSUE THREAD

**Issue by asltbbg** [Linuxfabrik/monitoring-plugins#654]
### Describe the solution you'd like

Thank you for fixing the credentials bug so fast.

It would be nice if the services which are disabled in the Loadbalancer would be displayed with the State [Disabled] not as [OK]

Not as warning or crit just as disabled
Maybe a triger option for max_disabled_services or known_disbled_services_count if warnings is an option

### Additional context

The REST API from the Kemp LB displays this state in Lines 2 and 7 in my eample:

<VS>
<Status>Disabled</Status>
<Index>7</Index>
<VSAddress>*********</VSAddress>
<VSPort>80</VSPort>
<Layer>7</Layer>
<NickName>Redirect ************</NickName>
<Enable>N</Enable>
<SSLReverse>N</SSLReverse>
<SSLReencrypt>N</SSLReencrypt>
<InterceptMode>0</InterceptMode>
<Intercept>N</Intercept>
<InterceptOpts>
....

**Comment by asltbbg** [comment]
The REST API from the Kemp LB displays this state in Lines 2 and 7 in my eample:

```
<VS>
<Status>Disabled</Status>
<Index>7</Index>
<VSAddress>*********</VSAddress>
<VSPort>80</VSPort>
<Layer>7</Layer>
<NickName>Redirect ************</NickName>
<Enable>N</Enable>
<SSLReverse>N</SSLReverse>
<SSLReencrypt>N</SSLReencrypt>
<InterceptMode>0</InterceptMode>
<Intercept>N</Intercept>
<InterceptOpts>
....

```

**Comment by markuslf** [comment]
* Output changed to be more clear
* Now also returns perfdata
