### ISSUE TITLE
ping: timeout error

### ISSUE THREAD

**Issue by gamebird92** [Linuxfabrik/monitoring-plugins#657]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] Compiled, from repo
- [ ] Source Code, from GitHub

### Bug description

Hey everyone,
I installed your awesome plugins for use in my icinga. I did import the templates into director and deploying my first host with one of your "tpl-host-generic" templates and leaving all data fields to template values. 

Strangely ping is runnning into an error:
when running 
`./ping '--count' '5' '--hostname' '192.168.73.249' '--intervall' '0.2' '--timeout' '5' `
it's telling me `ping: invalid argument: '5.0'`

Running `./ping '--count' '5' '--hostname' '192.168.73.249' '--intervall' '0.2' '--timeout' works. 

### Steps to reproduce - Plugin call

./ping '--count' '5' '--hostname' '192.168.73.249' '--intervall' '0.2' '--timeout' '5'

### Steps to reproduce - Data

ping: invalid argument: '5.0'

### Environment

Linux monitoring 5.15.0-67-generic

### Plugin Version

ping v2022021501 by Linuxfabrik GmbH, Zurich /Switzerland

### Python version

python 3.10.6

**Comment by markuslf** [comment]
Maybe `./ping' points to another ping command, not the one from our monitoring plugins. In any case, the `--interval' parameter is misspelled. What happens if you try `/usr/lib64/nagios/plugins/ping --count 5 --hostname 192.168.73.249 --interval 0.2 --timeout 5` directly on the command line?

**Comment by gamebird92** [comment]
When running ` /usr/lib64/nagios/plugins/ping --count 5 --hostname 192.168.73.249 --interval 0.2 --timeout 5` it's telling me:

```
root@monitoring:/lib64/nagios/plugins# ping --count 5 --hostname 192.168.73.249 --interval 0.2 --timeout 5
ping: invalid option -- '-'

```

So the "standard ping" is not pointing to your monitoring plugins I guess...

Running `root@monitoring:/lib64/nagios/plugins# ./ping --count 5 --hostname 192.168.73.249 --interval 0.2 --timeout 5` gives me the `ping: invalid argument: '5.0'` - the same error message I reveice from icinga... 

Sorry for the misspelled "intervall" - that was my mistake. Should have copied the text instead of typing it.

**Comment by markuslf** [comment]
Didn't get it in the first run, but you are using an outdated version. The error was fixed in https://github.com/Linuxfabrik/monitoring-plugins/issues/628. Please upgrade the checks to the latest release, including the [libs](https://github.com/Linuxfabrik/lib).

**Comment by gamebird92** [comment]
@markuslf oh i see the https://repo.linuxfabrik.ch/monitoring-plugins/ are not up to date. Thanks for your help!!!
