### ISSUE TITLE
Create multiple smaller checks for MySQL/MariaDB using logic from latest MySQLTuner

### ISSUE THREAD

**Issue by NavidSassan** [Linuxfabrik/monitoring-plugins#66]
In GitLab by @markuslf on Mar 23, 2020, 12:00

* split the check into multiple ones according to the sections from https://github.com/major/MySQLTuner-perl/blob/master/INTERNALS.md
* and make use of `lib/db_mysql3.py`
* be aware of https://github.com/Linuxfabrik/monitoring-plugins/issues/570

**Comment by markuslf** [comment]
It's done.
