### ISSUE TITLE
Question/Documentation: Are the tools to compile the download binary part of this repo?

### ISSUE THREAD

**Issue by cebe** [Linuxfabrik/monitoring-plugins#660]
### Describe the solution you'd like

I found that the plugins downloadable at https://download.linuxfabrik.ch/monitoring-plugins/zip/ are not python scripts but compiled binaries. 

I couldn't find any documentation on which arch they are compiled for and if there are external dependencies for the system which they are deployed to. I also couldn't find instructions on how to compile them. There is a [compile section for windows](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CONTRIBUTING.rst#compiling-for-windows) but I couldn't find anything for linux.

If this is already documented, please share the link, if not, I think it should documented so we can build the zip for a specific version of the repo.

Thanks!

**Comment by NavidSassan** [comment]
Hi, thanks for the input, makes sense :) Our end goal would be to automate the build using CI/CD, which would serve as implicit documentation. We will discuss internally where and how we can provide the documentation in the meantime.

**Comment by Domi-cc** [comment]
> If this is already documented, please share the link, if not, I think it should documented so we can build the zip for a specific version of the repo.

for specific version of the repo, also for specific OS

**Comment by markuslf** [comment]
Yes. I suggest that we
1. better explain in the README which version of the plugins can be used on which platform and how (incl. recommendation) and where to find what (github vs. download (and there exe vs. zip vs. tar)).
2. create a BUILD.md document describing the build process (or link to CI/CD) and link to it from the README.

**Comment by cebe** [comment]
> create a BUILD.md document describing the build process (or link to CI/CD) and link to it from the README.

Is the code for that currently publicly available (just not documented) or are you currently using private scripts for that?

**Comment by markuslf** [comment]
Currently using private scripts.

**Comment by jansagurna** [comment]
i would also be interested and could offer to test the scripts and help to find some bugs. For me it would be even more urgent, just have a current project.

**Comment by bgi** [comment]
to get the tools to compile would be great!

**Comment by cebe** [comment]
wow, that looks great. Thank you very much!

**Comment by Domi-cc** [comment]
we build a docker container to compile the plugins if it helps someone: https://github.com/we-push-it/linuxfabrik-plugin-builder

scripts are still in testing.
