### ISSUE TITLE
GLIBC_2.33 not found

### ISSUE THREAD

**Issue by mmartinello** [Linuxfabrik/monitoring-plugins#661]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] Compiled, from repo
- [ ] Source Code, from GitHub

### Bug description

The latest release (https://download.linuxfabrik.ch/monitoring-plugins/tar/linuxfabrik-monitoring-plugins-2023030801.tar) does not work on Debian Bullseye:

```
DEV root@dev1 /h/m/l/u/l/n/plugins# ./about-me
[326235] Error loading Python lib '/home/mattia/linuxfabrik-monitoring-plugins-2023030801/usr/lib64/nagios/plugins/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/mattia/linuxfabrik-monitoring-plugins-2023030801/usr/lib64/nagios/plugins/libpython3.9.so.1.0)
```

Libc is at version **2.31** on Debian Bullseye, which works with release **2022072001** (https://download.linuxfabrik.ch/monitoring-plugins/tar/linuxfabrik-monitoring-plugins-2022072001.tar).

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/about-me

### Steps to reproduce - Data

Install version 2023030801 on Debian Bullseye and execute the `about_me`plugin.
This problem probably happens with all plugins.

### Environment

Linux dev1 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux

### Plugin Version

Version 2023030801

### Python version

Python 3.9.2

**Comment by markuslf** [comment]
Why are you using the tar file and not the official repo at https://repo.linuxfabrik.ch/monitoring-plugins/debian/? (besides the fact that the packages there are currently not up to date because we are waiting for feedback for the next release)

**Comment by markuslf** [comment]
Somehow related to https://github.com/Linuxfabrik/monitoring-plugins/issues/660

**Comment by mmartinello** [comment]
> Just curious: Why are you using the tar file and not the official repo at https://repo.linuxfabrik.ch/monitoring-plugins/debian/? (besides the fact that the packages there are currently not up to date because we are waiting for feedback for the next release)

I'm also using APT archives, I just wanted to try the `.tar.gz` archive because I saw that is at a newer version.
As the version **2023030801** is considered stable there I added this just to let you know that it is not working on Bullseye which is officially supported.
