### ISSUE TITLE
disk-usage: Add include mount points/fs

### ISSUE THREAD

**Issue by drapiti** [Linuxfabrik/monitoring-plugins#662]
### Describe the solution you'd like

file systems in large entriprises may be supported by different teams based on application or technology. Therefore only certain filesystems are to be addressed to a specific team, and not all as is the case at the moment. Furthermore some file systems comply with automatic remediation processes others need to be addressed manually. To address all these issues this check needs to include the possibilty to select specific file systems and not just exclude them.

**Comment by markuslf** [comment]
Sounds reasonable.
