### ISSUE TITLE
disk-usage: Make plugin output more generic

### ISSUE THREAD

**Issue by log1-c** [Linuxfabrik/monitoring-plugins#664]
### Describe the solution you'd like

I'd like to propose a change to the way the plugin displays its output.
Currently the check display the first disk found as the short message:
![image](https://user-images.githubusercontent.com/24474580/232730506-d3b03ad1-3ef6-4739-9e6d-9614537bbeb3.png)

In the current state of the check where it checks all disks at once I find that a bit misleading, so that one could think that there is an issue with this disk.
I would like it if the plugin displays a more generic message like "All disks below thresholds" or something similar and show the table in the extended output message.

As I have also just seen the FR for checking a single mountpoint (https://github.com/Linuxfabrik/monitoring-plugins/issues/662), the current check output would fit that scenario. Checking a single mount point and then display said mountpoints statistics in the short message without any additional table.

**Comment by markuslf** [comment]
Yes, perfectly related to https://github.com/Linuxfabrik/monitoring-plugins/issues/662.
