### ISSUE TITLE
All: 'Unable to load parent referenced from service' when restoring the json file

### ISSUE THREAD

**Issue by Elikill58** [Linuxfabrik/monitoring-plugins#667]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] Source Code, from GitHub

### Bug description

I have this logs:
```
Unable to load parent referenced from service "Top3 Processes Which Caused The Most I/O", failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'tpl-service-top3-processes-which-caused-the-most-io' AND object_type = 'template' (IcingaObjectImports.php:273)
```

### Steps to reproduce - Plugin call

`icingacli director basket restore < icingaweb2-module-director-basket-no-uuids.json -v`

### Steps to reproduce - Data

Simply the one described [here](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/ICINGA.rst) in the "ALL plugins" sections

It's the same when using the web UI, when clicking "restore"

### Environment

Debian 5.10.0-21-amd64

### Plugin Version

All - with this commit: 8d50ac9dc42fb0d0a789184e61a9b78a36df723c

**Comment by markuslf** [comment]
The last of our "Top3" checks was moved into [disk-io](https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/disk-io).
See:
* [Issue](https://github.com/Linuxfabrik/monitoring-plugins/issues/285)
* [CHANGELOG](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CHANGELOG.md)
* [Commit](https://github.com/Linuxfabrik/monitoring-plugins/commit/2fd409be915fc8e2a37d23d0f6f1da7517768092)

I just forgot to clean up the [all-the-rest.json](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/assets/icingaweb2-module-director/all-the-rest.json). Thanks for reporting.
