### ISSUE TITLE
veeam: 'str' object has no attribute 'fetch_json'

### ISSUE THREAD

**Issue by asltbbg** [Linuxfabrik/monitoring-plugins#668]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] Compiled, from repo
- [X] Source Code, from GitHub

### Bug description

since the removing the "3" suffix

the veeam and the huawei plugins are throwing exceptions 

lib/huawei.py", line 43, in get_creds
    result = base.coe(url.fetch_json(
AttributeError: 'str' object has no attribute 'fetch_json'

lib/veeam.py", line 43, in get_token
    success, result = url.fetch_json(
AttributeError: 'str' object has no attribute 'fetch_json'

### Steps to reproduce - Plugin call

x

### Environment

5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Plugin Version

git

**Comment by markuslf** [comment]
Fixed in https://github.com/Linuxfabrik/lib/commit/498d6fdd03c37d75926b65e9cd7650d741227d45. Please test.
