### ISSUE TITLE
debian package: postinst error & selinux

### ISSUE THREAD

**Issue by Yoda-BZH** [Linuxfabrik/monitoring-plugins#674]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

When installing the debian package at version 2023051201, there's an error at postinst:
```
# apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  linuxfabrik-monitoring-plugins
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 198 MB of archives.
After this operation, 36.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://repo.linuxfabrik.ch/monitoring-plugins/debian bullseye-release/main amd64 linuxfabrik-monitoring-plugins all 2023051201 [198 MB]
Fetched 198 MB in 4s (49.6 MB/s)                         
(Reading database ... 261536 files and directories currently installed.)
Preparing to unpack .../linuxfabrik-monitoring-plugins_2023051201_all.deb ...
Unpacking linuxfabrik-monitoring-plugins (2023051201) over (2022072001) ...
Setting up linuxfabrik-monitoring-plugins (2023051201) ...
/var/lib/dpkg/info/linuxfabrik-monitoring-plugins.postinst: 1: restorecon: not found
/var/lib/dpkg/info/linuxfabrik-monitoring-plugins.postinst: 2: setsebool: not found
dpkg: error processing package linuxfabrik-monitoring-plugins (--configure):
 installed linuxfabrik-monitoring-plugins package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 linuxfabrik-monitoring-plugins
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```
# cat /var/lib/dpkg/info/linuxfabrik-monitoring-plugins.postinst
restorecon -r /usr/lib64/nagios
setsebool -P nagios_run_sudo on
```

Selinux

### Steps to reproduce - Plugin call

-

### Environment

debian stable
```
# uname -a
Linux servername 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### Plugin Version

2023051201

### List of Python modules

-

### Additional Information

reverting to 2022072001 fixes the problem.

Testing for selinux capability could be done before calling `restorecon`/`setsebool`

**Comment by markuslf** [comment]
Fixed.

**Comment by Yoda-BZH** [comment]
2023051201-3 fixed the problem.

Thanks !
