### ISSUE TITLE
qts-*: 'Keyerror: func' while executing qts-plugins

### ISSUE THREAD

**Issue by dishorned** [Linuxfabrik/monitoring-plugins#692]
Hi guys,

I have an Icinga2/Icingaweb2/Icinga Director installation and everything is working great. I use some of your plugins for my linux VMs and as well, the plugins (example: cpu-usage) are working great.

I also want to use the qts-plugins for my qnap nas (example: qts-memory-usage) but I always get the error 'Keyerror: func' in line 156. In the named plugin, it is the float-function for the total amount of memory.

`Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/c_check_qts-memory-usage", line 181, in 'module'
    main()
  File "/usr/lib/nagios/plugins/c_check_qts-memory-usage", line 156, in main
    total = float(data['func']['ownContent']['root']['total_memory']) * 1024 * 1024
KeyError: 'func'`

Do I miss something? Do you know, why I get this error?

Thanks a lot in advance and best regards

**Comment by NavidSassan** [comment]
Hi, what was the missing permission? Then we can adjust the README of the check-plugin :)

**Comment by dishorned** [comment]
Hi,
nothing special, but the check-user must be a member of the "administrators" group. It is not enough to be a member of the "everyone" group.

I tried to make a new group, with just the rights needed, but the only thing you can configure is share-access within group-configuration. So the check-user now has NO access to any share, but he is in the administrators-group. So it seems, that the administrators-group has a non-visible configuration to access the hardware-information.

It would be nice to create a group with only the right to read hardware information without admin-rights. But I don't know if that is possible, but it would be more secure. Maybe I check that later in the qnap documentation.

**Comment by markuslf** [comment]
Let me reopen this, want to implement better exception handling.
