### ISSUE TITLE
qts-version: Shows up to date even when new firmware available

### ISSUE THREAD

**Issue by dishorned** [Linuxfabrik/monitoring-plugins#693]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [X] Source Code from GitHub

### Bug description

The plugin reports the correct firmware version installed, but it says that it is up to date, even when a newer firmware available. This is the current output of the plugin:

`QTS v5.0.1.2376 Build 20230421 is up to date`

The newest version available is 5.0.1.2444 Build 20230629. After login to the QNAP GUI, the firmware version update window opens. So the version must be for my model.

### Steps to reproduce - Plugin call

'/usr/lib/nagios/plugins/c_check_qts-version' '--insecure' '--password' 'xxx' '--url' 'https://qnap.domain.tld:4444' '--username' 'xxx'

### Environment

Linux hostname 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

### Plugin Version

v2023071203

### Python version

3.9.2

**Comment by markuslf** [comment]
Tested with QTS v4.5.6, v5.0.1 and v5.1.0 - works as expected. Please try the newest [libs](https://github.com/Linuxfabrik/lib) and the newest version of this plugin.

**Comment by dishorned** [comment]
Hi markuslf,

first of all, thanks for your work!
I downloaded all the new libs and replaced the old ones.  Additonally I downloaded the new QTS-Version plugin and replaced that one as well, but on my system, the output is still 

`QTS v5.1.2.2533 Build 20230926 is up to date`

But when I go to the Qnap GUI and check for new update, it says there is one available:

`5.1.3.2578 build 20231110`

Do I missing something or do you think they have changed something in a minor version of QTS 5.1 again?

Side note: The Disk-Smart plugin now works again since the changes. I had problem with that one as well.

Thanks and best regards

**Comment by markuslf** [comment]
Hmmm... in this case it would help a lot if you could send me the output of these two `curl`-calls:
* `https://<YOUR-NAS>/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1&sid=<YOUR-SESSION-ID>`
* `https://<YOUR-NAS>/cgi-bin/sys/sysRequest.cgi?subfunc=firm_update&sid=<YOUR-SESSION-ID>`

**Comment by dishorned** [comment]
I would like to help, but I am not so versed in this topic. Which SID should be used? I think the user-session Icinga uses to connect to the Qnap NAS. I see that this special user has an open connection to the NAS but I don't know how to get the session id of that user. May you can help with that?

As a workaround, I logged in to the NAS and used the SessionID from the browser to connect with curl. Than I tried the following commands (with both HTTPS urls you gave me):

`curl --insecure https://....`
`curl --insecure -U $USERNAME$ https.//...`

But I got nothing special. Sometimes only three lines containing a number and sometimes something like:

`<authPassed><![CDATA[0]]></authPassed></QDocRoot>`

If you can give me a hint here, I will send you the needed output.

Thanks in advance and best regards

**Comment by markuslf** [comment]
Use Bash and do this.

Adapt this to your environment:
```
HOST=192.0.2.74:8080
USER=admin
PASS=linuxfabrik
```

Do the login and get the authSid:
```
curl \
    --data "user=${USER}&pwd=$(echo -n ${PASS} | base64)" \
    --insecure \
    --request POST \
    --silent \
    "https://${HOST}/cgi-bin/authLogin.cgi" | grep -E 'authSid(.*)/authSid'
```

Search for `<authSid><![CDATA[myauthsid]]></authSid>` in output (your session ID).

Please give me the output of the following commands:
```
curl \
    --insecure \
    --silent \
    "https://${HOST}/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1&sid=<YOUR-SESSION-ID>"
```

```
curl \
    --insecure \
    --silent \
    "https://${HOST}/cgi-bin/sys/sysRequest.cgi?subfunc=firm_update&sid=<YOUR-SESSION-ID>"

```

**Comment by dishorned** [comment]
Thanks for the help. Here is the output of the first command:

`<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[1]]></authPassed><model><modelName><![CDATA[TS-XA73]]></modelName><internalModelName><![CDATA[TS-XA73]]></internalModelName><platform><![CDATA[TS-NASX86]]></platform><platform_ex><![CDATA[X86_MERLINFALCON]]></platform_ex><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-673]]></displayModelName><sas_model><![CDATA[0]]></sas_model><storage_v2>1</storage_v2>
<encryptfsSupported><![CDATA[1]]></encryptfsSupported><is_zfs><![CDATA[0]]></is_zfs><node><![CDATA[]]></node><dual_node><![CDATA[]]></dual_node></model>
<firmware><name><![CDATA[QTS]]></name><version><![CDATA[5.1.2]]></version><number><![CDATA[2533]]></number><build><![CDATA[20230926]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[2023/09/26]]></buildTime></firmware>
<rfs_bits><![CDATA[64]]></rfs_bits><specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[nas01]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<func><name><![CDATA[S_MENU_40]]></name><ownContent><root>
<timezone><![CDATA[(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna]]></timezone><cpu_usage><![CDATA[5.1 %]]></cpu_usage><cpufan_count>1</cpufan_count>
<cpufan1>1175</cpufan1>
<fan_fail1>0</fan_fail1>
<fan_reg_cnt><![CDATA[0]]></fan_reg_cnt><temp_reg_cnt><![CDATA[0]]></temp_reg_cnt><cpu_model><![CDATA[AMD Embedded R-Series RX-421ND]]></cpu_model><cpu_model_name><![CDATA[AMD Embedded R-Series RX-421ND]]></cpu_model_name><cpu_burst_freq><![CDATA[2100 MHz]]></cpu_burst_freq><total_memory><![CDATA[15967.0]]></total_memory><free_memory><![CDATA[12819.7]]></free_memory><memory_below_recommended_size><![CDATA[0]]></memory_below_recommended_size><mem_info_support><![CDATA[1]]></mem_info_support><mem_max_channels><![CDATA[2]]></mem_max_channels><mem_max_slots><![CDATA[4]]></mem_max_slots><mem_slot_info><mem_valid><![CDATA[1]]></mem_valid><mem_slot_id><![CDATA[1]]></mem_slot_id><mem_dimm_id><![CDATA[1]]></mem_dimm_id><mem_channel_id><![CDATA[A]]></mem_channel_id><mem_dimm_size><![CDATA[8192]]></mem_dimm_size><mem_module_type><![CDATA[3]]></mem_module_type><mem_ecc_support><![CDATA[0]]></mem_ecc_support><mem_dimm_manufacturer><![CDATA[Kingston]]></mem_dimm_manufacturer><mem_slot_color><![CDATA[0]]></mem_slot_color></mem_slot_info>
<mem_slot_info><mem_valid><![CDATA[0]]></mem_valid><mem_slot_id><![CDATA[2]]></mem_slot_id><mem_dimm_id><![CDATA[2]]></mem_dimm_id><mem_channel_id><![CDATA[A]]></mem_channel_id><mem_dimm_size><![CDATA[0]]></mem_dimm_size><mem_module_type><![CDATA[0]]></mem_module_type><mem_ecc_support><![CDATA[0]]></mem_ecc_support><mem_dimm_manufacturer><![CDATA[]]></mem_dimm_manufacturer><mem_slot_color><![CDATA[0]]></mem_slot_color></mem_slot_info>
<mem_slot_info><mem_valid><![CDATA[1]]></mem_valid><mem_slot_id><![CDATA[3]]></mem_slot_id><mem_dimm_id><![CDATA[3]]></mem_dimm_id><mem_channel_id><![CDATA[B]]></mem_channel_id><mem_dimm_size><![CDATA[8192]]></mem_dimm_size><mem_module_type><![CDATA[3]]></mem_module_type><mem_ecc_support><![CDATA[0]]></mem_ecc_support><mem_dimm_manufacturer><![CDATA[Kingston]]></mem_dimm_manufacturer><mem_slot_color><![CDATA[0]]></mem_slot_color></mem_slot_info>
<mem_slot_info><mem_valid><![CDATA[0]]></mem_valid><mem_slot_id><![CDATA[4]]></mem_slot_id><mem_dimm_id><![CDATA[4]]></mem_dimm_id><mem_channel_id><![CDATA[B]]></mem_channel_id><mem_dimm_size><![CDATA[0]]></mem_dimm_size><mem_module_type><![CDATA[0]]></mem_module_type><mem_ecc_support><![CDATA[0]]></mem_ecc_support><mem_dimm_manufacturer><![CDATA[]]></mem_dimm_manufacturer><mem_slot_color><![CDATA[0]]></mem_slot_color></mem_slot_info>
<mem_slot_color_support><![CDATA[0]]></mem_slot_color_support><nic_cnt><![CDATA[8]]></nic_cnt><nic_lan_cnt><![CDATA[8]]></nic_lan_cnt><nic_qa_port_cnt><![CDATA[0]]></nic_qa_port_cnt><ifindex1>4</ifindex1>
<ifname1>eth0</ifname1>
<dname1>Adapter 1</dname1>
<rx_packet1>0</rx_packet1>
<tx_packet1>0</tx_packet1>
<err_packet1>0</err_packet1>
<eth_status1>0</eth_status1>
<eth_max_speed1>1000</eth_max_speed1>
<is_QA_port_eth1>0</is_QA_port_eth1>
<eth_ip1>0.0.0.0</eth_ip1>
<eth_mask1>0.0.0.0</eth_mask1>
<eth_mac1>24:5e:be:00:00:00</eth_mac1>
<eth_usage1>STATIC</eth_usage1>
<eth_ipv6_info1><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info1><dnsinfo1><dns1>10.0.0.0</dns1>
</dnsinfo1><ifindex2>5</ifindex2>
<ifname2>eth1</ifname2>
<dname2>Adapter 2</dname2>
<rx_packet2>0</rx_packet2>
<tx_packet2>0</tx_packet2>
<err_packet2>0</err_packet2>
<eth_status2>0</eth_status2>
<eth_max_speed2>1000</eth_max_speed2>
<is_QA_port_eth2>0</is_QA_port_eth2>
<eth_ip2>0.0.0.0</eth_ip2>
<eth_mask2>0.0.0.0</eth_mask2>
<eth_mac2>24:5e:be:00:00:00</eth_mac2>
<eth_usage2>DHCP</eth_usage2>
<eth_ipv6_info2><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info2><dnsinfo2><dns1>10.0.0.0</dns1>
<dns2>10.0.0.0</dns2>
</dnsinfo2><ifindex3>3</ifindex3>
<ifname3>eth2</ifname3>
<dname3>Adapter 3</dname3>
<rx_packet3>0</rx_packet3>
<tx_packet3>0</tx_packet3>
<err_packet3>0</err_packet3>
<eth_status3>0</eth_status3>
<eth_max_speed3>1000</eth_max_speed3>
<is_QA_port_eth3>0</is_QA_port_eth3>
<eth_ip3>0.0.0.0</eth_ip3>
<eth_mask3>0.0.0.0</eth_mask3>
<eth_mac3>24:5e:be:00:00:00</eth_mac3>
<eth_usage3>DHCP</eth_usage3>
<eth_ipv6_info3><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info3><dnsinfo3><dns1>10.0.0.0</dns1>
<dns2>10.0.0.0</dns2>
</dnsinfo3><ifindex4>2</ifindex4>
<ifname4>eth3</ifname4>
<dname4>Adapter 4</dname4>
<rx_packet4>0</rx_packet4>
<tx_packet4>0</tx_packet4>
<err_packet4>0</err_packet4>
<eth_status4>0</eth_status4>
<eth_max_speed4>1000</eth_max_speed4>
<is_QA_port_eth4>0</is_QA_port_eth4>
<eth_ip4>0.0.0.0</eth_ip4>
<eth_mask4>0.0.0.0</eth_mask4>
<eth_mac4>24:5e:be:00:00:00</eth_mac4>
<eth_usage4>DHCP</eth_usage4>
<eth_ipv6_info4><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info4><dnsinfo4><dns1>10.0.0.0</dns1>
<dns2>10.0.0.0</dns2>
</dnsinfo4><ifindex5>9</ifindex5>
<ifname5>eth5</ifname5>
<dname5>Adapter 5</dname5>
<rx_packet5>680403927</rx_packet5>
<tx_packet5>571654394</tx_packet5>
<err_packet5>0</err_packet5>
<eth_status5>1</eth_status5>
<eth_max_speed5>2500</eth_max_speed5>
<is_QA_port_eth5>0</is_QA_port_eth5>
<eth_ip5>10.0.0.0</eth_ip5>
<eth_mask5>255.255.255.0</eth_mask5>
<eth_mac5>24:5e:be:00:00:00</eth_mac5>
<eth_usage5>STATIC</eth_usage5>
<eth_ipv6_info5><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info5><dnsinfo5><dns1>10.0.0.0</dns1>
</dnsinfo5><ifindex6>8</ifindex6>
<ifname6>eth6</ifname6>
<dname6>Adapter 6</dname6>
<rx_packet6>0</rx_packet6>
<tx_packet6>0</tx_packet6>
<err_packet6>0</err_packet6>
<eth_status6>0</eth_status6>
<eth_max_speed6>2500</eth_max_speed6>
<is_QA_port_eth6>0</is_QA_port_eth6>
<eth_ip6>0.0.0.0</eth_ip6>
<eth_mask6>0.0.0.0</eth_mask6>
<eth_mac6>24:5e:be:00:00:00</eth_mac6>
<eth_usage6>DHCP</eth_usage6>
<eth_ipv6_info6><eth_ipv6_enable>1</eth_ipv6_enable></eth_ipv6_info6><dnsinfo6></dnsinfo6><ifindex7>7</ifindex7>
<ifname7>eth7</ifname7>
<dname7>Adapter 7</dname7>
<rx_packet7>0</rx_packet7>
<tx_packet7>0</tx_packet7>
<err_packet7>0</err_packet7>
<eth_status7>0</eth_status7>
<eth_max_speed7>2500</eth_max_speed7>
<is_QA_port_eth7>0</is_QA_port_eth7>
<eth_ip7>0.0.0.0</eth_ip7>
<eth_mask7>0.0.0.0</eth_mask7>
<eth_mac7>24:5e:be:00:00:00</eth_mac7>
<eth_usage7>DHCP</eth_usage7>
<eth_ipv6_info7><eth_ipv6_enable>1</eth_ipv6_enable></eth_ipv6_info7><dnsinfo7></dnsinfo7><ifindex8>6</ifindex8>
<ifname8>eth8</ifname8>
<dname8>Adapter 8</dname8>
<rx_packet8>680403941</rx_packet8>
<tx_packet8>571654403</tx_packet8>
<err_packet8>0</err_packet8>
<eth_status8>1</eth_status8>
<eth_max_speed8>2500</eth_max_speed8>
<is_QA_port_eth8>0</is_QA_port_eth8>
<eth_ip8>10.0.0.0</eth_ip8>
<eth_mask8>255.255.255.0</eth_mask8>
<eth_mac8>24:5e:be:00:00:00</eth_mac8>
<eth_usage8>STATIC</eth_usage8>
<eth_ipv6_info8><eth_ipv6_enable>0</eth_ipv6_enable></eth_ipv6_info8><dnsinfo8><dns1>10.0.0.0</dns1>
</dnsinfo8><bonding_list><bonding_info><ifindex>11</ifindex>
<ifname>bond1</ifname>
<dname>Adapter 5+8</dname>
<rx_packet>680403941</rx_packet>
<tx_packet>571654403</tx_packet>
<err_packet>0</err_packet>
<if_status>1</if_status>
<if_max_speed>0</if_max_speed>
<if_ip>10.0.0.0</if_ip>
<if_mask>255.255.255.0</if_mask>
<if_mac>24:5E:BE:00:00:00</if_mac>
<if_usage>STATIC</if_usage>
<if_member_cnt>2</if_member_cnt><if_member_info><if_member1>eth5</if_member1><if_member2>eth8</if_member2></if_member_info><if_ipv6_info><if_ipv6_enable>0</if_ipv6_enable></if_ipv6_info><dnsinfo><dns1>10.0.0.0</dns1>
</dnsinfo></bonding_info>
</bonding_list>
<bonding_cnt><![CDATA[1]]></bonding_cnt><ipv6Enable><![CDATA[1]]></ipv6Enable><dnsInfo><DNS_LIST><![CDATA[ 10.0.0.0
]]></DNS_LIST><DNS_LIST><![CDATA[ 10.0.0.0]]></DNS_LIST></dnsInfo>
<WirelessSupport><![CDATA[1]]></WirelessSupport><Error><![CDATA[1]]></Error><ThunderboltSupport><![CDATA[0]]></ThunderboltSupport><uptime_day><![CDATA[34]]></uptime_day><uptime_hour><![CDATA[8]]></uptime_hour><uptime_min><![CDATA[55]]></uptime_min><uptime_sec><![CDATA[55]]></uptime_sec><HDTempWarnT><![CDATA[55]]></HDTempWarnT><HDTempErrT><![CDATA[60]]></HDTempErrT><SSDTempWarnT><![CDATA[70]]></SSDTempWarnT><SSDTempErrT><![CDATA[70]]></SSDTempErrT><cpu_tempc>61</cpu_tempc><cpu_tempf>141</cpu_tempf>
<CPUTempWarnT><![CDATA[75]]></CPUTempWarnT><CPUTempErrT><![CDATA[80]]></CPUTempErrT><system_temp_count><![CDATA[1]]></system_temp_count><sys_tempc>43</sys_tempc>
<sys_tempf>109</sys_tempf>
<SysTempWarnT><![CDATA[60]]></SysTempWarnT><SysTempErrT><![CDATA[70]]></SysTempErrT><tpu><tpu_dev_cnt><![CDATA[0]]></tpu_dev_cnt></tpu>
<hailo_8><hailo_8_dev_cnt><![CDATA[0]]></hailo_8_dev_cnt></hailo_8>
<sysfan_count>2</sysfan_count>
<sysfan_alias>SYS FAN</sysfan_alias>
<sysfan1>813</sysfan1>
<sysfan_fail1>0</sysfan_fail1>
<sysfan1_stat>0</sysfan1_stat>
<sysfan2>834</sysfan2>
<sysfan_fail2>0</sysfan_fail2>
<sysfan2_stat>0</sysfan2_stat>
<Power1Temp>-1</Power1Temp>
<Power1Status>0</Power1Status>
<PowerFanStatus1>-1</PowerFanStatus1>
<BusType>NAS</BusType>
<serial_number>xxxx</serial_number>
<server_name><![CDATA[nas01]]></server_name><qat_support><![CDATA[0]]></qat_support><codepage><![CDATA[850]]></codepage><bios_version>QY03AR53</bios_version>
</root>
</ownContent>
</func>
</QDocRoot>`

And the output of the second command:

`<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[1]]></authPassed><model><modelName><![CDATA[TS-XA73]]></modelName><internalModelName><![CDATA[TS-XA73]]></internalModelName><platform><![CDATA[TS-NASX86]]></platform><platform_ex><![CDATA[X86_MERLINFALCON]]></platform_ex><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-673]]></displayModelName><sas_model><![CDATA[0]]></sas_model><storage_v2>1</storage_v2>
<encryptfsSupported><![CDATA[1]]></encryptfsSupported><is_zfs><![CDATA[0]]></is_zfs><node><![CDATA[]]></node><dual_node><![CDATA[]]></dual_node></model>
<firmware><name><![CDATA[QTS]]></name><version><![CDATA[5.1.2]]></version><number><![CDATA[2533]]></number><build><![CDATA[20230926]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[2023/09/26]]></buildTime></firmware>
<rfs_bits><![CDATA[64]]></rfs_bits><specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[nas01]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<func><name><![CDATA[S_MENU_9]]></name><ownContent><fileMD5><![CDATA[null]]></fileMD5><Result><![CDATA[0]]></Result><uptimeSec><![CDATA[2969835]]></uptimeSec><rebootSuggest><![CDATA[1]]></rebootSuggest><countryCode><code><![CDATA[000000]]></code><abbr><![CDATA[GLB]]></abbr><name><![CDATA[Global]]></name></countryCode>
<update_lock><![CDATA[0]]></update_lock><agree_beta><![CDATA[0]]></agree_beta><desktop_check_fw><![CDATA[1]]></desktop_check_fw><agree_downgrade><![CDATA[0]]></agree_downgrade><agree_code_signing_status><![CDATA[0]]></agree_code_signing_status><liveUpdateStatus><![CDATA[done]]></liveUpdateStatus><official><new_feature_url><![CDATA[]]></new_feature_url><newVersion><![CDATA[none]]></newVersion></official>
<recommended><new_feature_url><![CDATA[]]></new_feature_url><newVersion><![CDATA[none]]></newVersion></recommended>
<updateCheckTime><![CDATA[2023/11/23 10:38:31]]></updateCheckTime><dateformatindex><![CDATA[1]]></dateformatindex><timeformat><![CDATA[24]]></timeformat><updateFinishTime><![CDATA[2023/10/20 11:51:49]]></updateFinishTime><doReboot><![CDATA[0]]></doReboot><update_remind_time><![CDATA[0]]></update_remind_time><mcu><mcu_version><![CDATA[--]]></mcu_version><mcu_need_update><![CDATA[0]]></mcu_need_update></mcu>
<code_signing_information><IgnoreCodeSigning><![CDATA[0]]></IgnoreCodeSigning><issued_by><![CDATA[QNAP]]></issued_by><issued_to><![CDATA[QNAP]]></issued_to><valid_from><![CDATA[2022/03/17 13:51:18]]></valid_from><valid_to><![CDATA[2025/03/16 13:51:18]]></valid_to><owner><![CDATA[QNAP]]></owner><issued_on><![CDATA[2023/09/26 00:36:16]]></issued_on><expired><![CDATA[0]]></expired></code_signing_information>
</ownContent>
</func>
<sleepSupport><![CDATA[0]]></sleepSupport></QDocRoot>`

I just changed the IP and MAC addresses.

I hope it helps. Thanks a lot.

**Comment by markuslf** [comment]
Thank you. The plugin is correct. According to the data returned by your QTS appliance, there is no newer version applicable. Your NAS reports in its 2nd answer:
```
<firmware>
    <name>
    <![CDATA[QTS]]>
</name>
<version>
    <![CDATA[5.1.2]]>
</version>
<number>
    <![CDATA[2533]]>
</number>
<build>
    <![CDATA[20230926]]>
</build>
<patch>
    <![CDATA[0]]>
</patch>
<buildTime>
    <![CDATA[2023/09/26]]>
</buildTime>
</firmware> 
```
This is exact the same version you have currently installed (from its 1st answer):
```
<firmware>
    <name>
    <![CDATA[QTS]]>
</name>
<version>
    <![CDATA[5.1.2]]>
</version>
<number>
    <![CDATA[2533]]>
</number>
<build>
    <![CDATA[20230926]]>
</build>
<patch>
    <![CDATA[0]]>
</patch>
<buildTime>
    <![CDATA[2023/09/26]]>
</buildTime>
</firmware> 
```
This may be due to some QNAP-specific update behavior (updates may be distributed in chunks). The QNAP-GUI seems to use some other info channel than the API. I will close this issue.

**Comment by dishorned** [comment]
Hey markuslf,

thanks for checking that. Sometimes there updates are critical because they close some serious vulnerabilities, so I am wondering, that the API still shows up2date even the timestamp of the update is 2 weeks old.

I will keep an eye on it, when the API recognizes/finds the new version.

Again, thanks a lot for your help and work. Keep on with it!
