### ISSUE TITLE
php-version: Check multiple installed PHP versions

### ISSUE THREAD

**Issue by sf-rag** [Linuxfabrik/monitoring-plugins#694]
### Describe the solution you'd like

We use the PHP Sury repository to have multiple PHP versions installed at the same time.
The current php-version plugin does only check the default PHP version.

Would it be possible to either add a flag (`--php-base-version` for example) that allows to specify these other versions? This would be trivial to add to the current script.
Another way could be to check if different PHP-Versions are installed on the system. This would require a modified `get_installed_version()`. Theoretically one could loop over the versions retrieved by https://endoflife.date/api/php.json and call `php{base_version} --version` for each one.

**Comment by markuslf** [comment]
On how to implement that, see python-version (`--path` parameter). @lfchris
