### ISSUE TITLE
qts-version error on TS-469L

### ISSUE THREAD

**Issue by kPentagramm** [Linuxfabrik/monitoring-plugins#701]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [X] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

When I try to check for the qts-version on a TS-469L-nas I get this error in 
![Screenshot 2023-08-11 105011](https://github.com/Linuxfabrik/monitoring-plugins/assets/107259807/0ee729e3-52dd-4c33-b1fd-4c56f28097d0)

The plugin works fine on a TS1232XU

### Steps to reproduce - Plugin call

'/usr/lib64/nagios/plugins/qts-version' '--insecure' '--password' 'XXX' '--timeout' '120' '--url' 'https://XXX.XXX.XXX.XXX' '--username' 'XXX'

### Steps to reproduce - Data

Output of the call directly on the icinga-server:
![Screenshot 2023-08-11 105852](https://github.com/Linuxfabrik/monitoring-plugins/assets/107259807/ecbd3e60-9799-487c-81db-311a6af1c88f)

### Environment

Icinga2-Version: 2.14.0-1
Icingaweb2: 2.11.4
Director: 1.9.1

### Plugin Version

v2023051201

**Comment by markuslf** [comment]
Which versions of QTS do you use
* on TS1232XU (working)
* on TS-469L (not working)?

**Comment by kPentagramm** [comment]
On the TS1232XU: QTS 5.0.1.2425
On the TS-469L: QTS 4.3.4.2451

**Comment by markuslf** [comment]
Interesting. Can TS-469L be upgraded to v5? If so, and if it works after that, I will update the README to mention the minimum requirements.

**Comment by kPentagramm** [comment]
Sadly no. 4.3.4.2451 is the latest Firmware that is available for it.

**Comment by markuslf** [comment]
Then we will leave the plugin as it is. It makes no sense for us to support EOL software and hardware. I will update the README.
