### ISSUE TITLE
rpm-lastactivity: make a deb or combine into a package-lastactivity version

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#705]
### Describe the solution you'd like

See title

### Additional context

`dpkg-query --show -f='${db-fsys:Last-Modified} ${Package}\n' '*' | grep -v '^ '` could be a drop in replacement for `rpm --query --all --queryformat "%{INSTALLTIME} %{NAME}\n"` since dpkg 1.19.3.

**Comment by slalomsk8er** [comment]
@markuslf what do you think, 2 separate or a merged version? My rationale would be a merged version because both commands produce the same output so duplicated the logic would be a waste.

**Comment by markuslf** [comment]
Implemented via #710
