### ISSUE TITLE
csv-values: header included in data results despite setting "--skip-header"

### ISSUE THREAD

**Issue by bangerer** [Linuxfabrik/monitoring-plugins#706]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [X] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Hello!

I'm using the `csv-values` check with a small csv file (see below).

When executing the check, it also outputs the header of the csv from it's SQLite database, as if it was another data row.
This occurs in spite of setting "--skip-header" in the command call.

Therefore, in the plugin output and Icinga2's web overview, the header appears twice, once as a descriptive row and a second time as a data row (with the second time also increasing the count of the result set).

### Steps to reproduce - Plugin call

sudo -u nagios /usr/lib64/nagios/plugins/csv-values' '--chunksize' '1000' '--columns-query' 'username TEXT, failedlogin INTEGER' '--critical' '1' '--critical-query' 'SELECT * FROM data WHERE failedlogin > 10;' '--delimiter' ',' '--filename' '/tmp/monitoring.csv' '--quotechar' '"' '--skip-header' '--timeout' '3' '--warning' '1' '--warning-query' 'SELECT * FROM data WHERE failedlogin > 5 and failedlogin <= 10;

### Steps to reproduce - Data

Here's how my csv file looks:

```bash
cat /tmp/monitoring.csv

username,failedlogin
myfirstuser,15
myseconduser,1
```

On that file I've executed the above check plugin command, which results in the following output:

```bash
root@myserver:~# sudo -u nagios '/usr/lib64/nagios/plugins/csv-values' '--chunksize' '1000' '--columns-query' 'username TEXT, failedlogin INTEGER' '--critical' '1' '--critical-query' 'SELECT * FROM data WHERE failedlogin > 10;' '--delimiter' ',' '--filename' '/tmp/monitoring.csv' '--quotechar' '"' '--skip-header' '--timeout' '3' '--warning' '1' '--warning-query' 'SELECT * FROM data WHERE failedlogin > 5 and failedlogin <= 10;
'
0 results from warning query `SELECT * FROM data WHERE failedlogin > 5 and failedlogin <= 10;
` and 2 results from critical query `SELECT * FROM data WHERE failedlogin > 10;` [CRITICAL]

username ! failedlogin
---------+-------------
username ! failedlogin
myseconduser ! 15|'cnt_warn'=0;;;; 'cnt_crit'=2;;;;
```

In SQLite's shell, I can see that the header from the csv file was indeed inserted as another data row:

```bash
root@myserver:~# sqlite3 linuxfabrik-monitoring-plugins-csv-values-62b14152552defdc56d4ac403c646815169fe1b5.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> select * from data;
username|failedlogin
myfirstuser|15
myseconduser|1
```

### Environment

- Icinga2 2.14.0
- SQLite 3.34.1

### Plugin Version

csv-values: v2023051201 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

3.9.2

### List of Python modules

OpenSSL             abc                 gpg                 requests
PyICU               acme                graphlib            requests_toolbelt
__future__          aifc                gridfs              resolvelib
_abc                antigravity         grp                 resource
_aix_support        appdirs             gzip                retrying
_ast                apt                 hashlib             rlcompleter
_asyncio            apt_inst            heapq               runpy
_bisect             apt_pkg             hmac                samba
_blake2             aptsources          html                sched
_bootlocale         argparse            html5lib            secrets
_bootsubprocess     array               http                select
_bz2                ast                 httplib2            selectors
_cffi_backend       asynchat            icu                 setuptools
_codecs             asyncio             idna                shelve
_codecs_cn          asyncore            imaplib             shlex
_codecs_hk          atexit              imghdr              shutil
_codecs_iso2022     audioop             imp                 signal
_codecs_jp          base64              importlib           site
_codecs_kr          bdb                 inspect             sitecustomize
_codecs_tw          binascii            io                  six
_collections        binhex              ipaddr              smbc
_collections_abc    bisect              ipaddress           smtpd
_compat_pickle      bs4                 itertools           smtplib
_compression        bson                josepy              sndhdr
_contextvars        btrfs               json                socket
_crypt              builtins            keyword             socketserver
_csv                bz2                 ldb                 soupsieve
_ctypes             cProfile            lib2to3             spwd
_ctypes_test        cachecontrol        linecache           sqlite3
_curses             cairo               locale              sre_compile
_curses_panel       calendar            logging             sre_constants
_datetime           certbot             lsb_release         sre_parse
_dbm                certifi             lxml                ssl
_dbus_bindings      cgi                 lzma                stat
_dbus_glib_bindings cgitb               magic               statistics
_decimal            chardet             mailbox             string
_distutils_hack     chunk               mailcap             stringprep
_elementtree        cmath               marshal             struct
_functools          cmd                 math                subprocess
_hashlib            code                mimetypes           sunau
_heapq              codecs              mmap                symbol
_icu                codeop              modulefinder        symtable
_imp                collections         msgpack             sys
_io                 colorama            multiprocessing     sysconfig
_json               colorsys            nagiosplugin        syslog
_ldb_text           compileall          netrc               systemd
_locale             concurrent          nis                 tabnanny
_lsprof             configargparse      nntplib             talloc
_lzma               configobj           ntpath              tarfile
_markupbase         configparser        nturl2path          tdb
_md5                contextlib          numbers             telnetlib
_multibytecodec     contextvars         opcode              tempfile
_multiprocessing    copy                operator            termios
_opcode             copyreg             optparse            test
_operator           crypt               os                  textwrap
_osx_support        cryptography        ossaudiodev         this
_peg_parser         csv                 packaging           threading
_pickle             ctypes              parsedatetime       time
_posixshmem         cups                parser              timeit
_posixsubprocess    cupshelpers         pathlib             tinkerforge
_py_abc             curl                pdb                 token
_pydecimal          curses              pep517              tokenize
_pyio               dataclasses         pickle              toml
_queue              datetime            pickletools         trace
_random             dbm                 pip                 traceback
_sha1               dbus                pipes               tracemalloc
_sha256             deb822              pkg_resources       tty
_sha3               debconf             pkgutil             turtle
_sha512             debian              platform            types
_signal             debian_bundle       plistlib            typing
_sitebuiltins       debianbts           poplib              ufw
_smbc               decimal             posix               unicodedata
_socket             devscripts          posixpath           unidiff
_sqlite3            difflib             pprint              unittest
_sre                dis                 profile             urllib
_ssl                distlib             progress            urllib3
_stat               distro              pstats              uu
_statistics         distutils           psutil              uuid
_string             doctest             pty                 validate
_strptime           easy_install        pwd                 venv
_struct             email               py_compile          warnings
_symtable           encodings           pyclbr              wave
_sysconfigdata__linux_x86_64-linux-gnu enum                pycurl              weakref
_sysconfigdata__x86_64-linux-gnu errno               pydoc               webbrowser
_tdb_text           fail2ban            pydoc_data          webencodings
_testbuffer         faulthandler        pyexpat             wheel
_testcapi           fcntl               pygtkcompat         wsgiref
_testimportmultiple filecmp             pyinotify           xdg
_testinternalcapi   fileinput           pymongo             xdrlib
_testmultiphase     fnmatch             pymysql             xml
_thread             formatter           pyparsing           xmlrpc
_threading_local    fractions           pyrfc3339           xxlimited
_tracemalloc        ftplib              pysimplesoap        xxsubtype
_uuid               functools           pytz                zipapp
_version            gc                  queue               zipfile
_warnings           genericpath         quopri              zipimport
_weakref            getopt              random              zlib
_weakrefset         getpass             re                  zoneinfo
_xxsubinterpreters  gettext             readline            zope
_xxtestfuzz         gi                  reportbug
_zoneinfo           glob                reprlib

### Additional Information

Hopefully I didn't miss something obvious. ;)
Happy to help in debugging the issue.

Thanks for your hard work & bye,
Barney

**Comment by markuslf** [comment]
There was a little logic issue handling the `--skip-header` parameter. Thanks for reporting, fixed.
