### ISSUE TITLE
disk-io: Wildcard support for ignore disks

### ISSUE THREAD

**Issue by xeiss** [Linuxfabrik/monitoring-plugins#708]
### Describe the solution you'd like

I have some Linux servers with same dynamic created disk names. For example, hosts with SAN multipath creates many "sd*" disk, because each path (normal 4) creates an own disk which are absolute uninteresting because they will merge in "dm-*" disks. I/O info about sd* disks are useless because they can switch their names every reboot.

I do not want to set --ignore "sda" --ignore "sdb" … 52x times ... for each of this server.

Wildcard support. example: --ignore "sd*" should be possible.
Or regex support would be also possible.

**Comment by markuslf** [comment]
Fixed by https://github.com/Linuxfabrik/monitoring-plugins/commit/173edda33cfe511c9a7dd232434664bf71bf59c1
