### ISSUE TITLE
Error when running plugins: FATAL FIPS SELFTEST FAILURE

### ISSUE THREAD

**Issue by michaje-gsc** [Linuxfabrik/monitoring-plugins#711]
Hello,

This is probably an obvious issue to solve, as I am not a Linux expert.

I have downloaded the Linuxfabrik plugins and installed them on my test RHEL 8.8 server.  Most of them are giving me this FIPS error (exit code of previous command within parentheses):

```
(0) lut01# ./about-me
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
Aborted (core dumped)
(134) lut01# ls -la ./about-me
-rwxr-x---. 1 jean jean 1053608 May 12 14:33 about-me
(0) lut01# uname -r
4.18.0-477.15.1.el8_8.x86_64
(0) lut01#
```

Any help to make the plugins work would be highly appreciated.

Thank you,

Jean

**Comment by markuslf** [comment]
Output of `update-crypto-policies --show`?

**Comment by michaje-gsc** [comment]
> What is the output of update-crypto-policies --show?

`DEFAULT:NO-SHA1`

> If I start RHEL in FIPS mode

How can this be done?  Is it at least as secure as the current mode?

**Comment by markuslf** [comment]
So this is not a bug and beyond the scope of this monitoring-plugins project, but this should help you get started:
* `DEFAULT:NO-SHA1` means you have the default crypto policy running, with a custom modification of `NO-SHA1` (obviously you have turned off SHA1 support). Now something seems to be broken on your system.
* The `FIPS' mode ensures that your RHEL system generates and uses all cryptographic keys only with FIPS approved algorithms. See [Wikipedia](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) and [RHEL's documentation](https://access.redhat.com/documentation/de-de/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening).

**Comment by michaje-gsc** [comment]
One more question, please: is it mandatory to enable the `FIPS` mode in order to be able to run the Linuxfabrik plugins on RHEL 8.8?

**Comment by markuslf** [comment]
No. But whether you use `DEFAULT`, `FIPS`, or any other cryptographic mode, they work fine, so it looks like something is broken on your end.
