### ISSUE TITLE
rhel-version: EOL for Minor-Releases

### ISSUE THREAD

**Issue by koraz-0815** [Linuxfabrik/monitoring-plugins#740]
### Describe the solution you'd like

The plugin will check if the Minor-Version is in Extended Update Support and the EOL of this Minor Version.
https://access.redhat.com/support/policy/updates/errata#RHEL8_Planning_Guide
https://access.redhat.com/support/policy/updates/errata/#Extended_Update_Support
For example:
**8.4**: CRITICAL: EOL 31.05.2023
**8.6**: OK: EOL 31.05.2024
**8.8**: OK: EOL 31.05.2025

**Comment by markuslf** [comment]
The plugin checks against https://endoflife.date/rhel, and offers some parameters to control handling major, minor or patch updates, too (see https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/rhel-version for details). Checking ExtendedSupport is currently not supported by the plugin.

**Comment by koraz-0815** [comment]
> The plugin checks against https://endoflife.date/rhel

It ist possible to use a own website?
for example
```
    {
        "cycle": "88",
        "eol": "2025-05-31",
    },
        {
        "cycle": "86",
        "eol": "2024-05-31",
    },
    {
        "cycle": "84",
        "eol": "2023-05-31",
    },

**Comment by markuslf** [comment]
No.

**Comment by slalomsk8er** [comment]
Maybe https://cve.tuxcare.com/rss_feed/releases could be added

**Comment by markuslf** [comment]
> Maybe https://cve.tuxcare.com/rss_feed/releases could be added

Might be worth a separate plugin.

**Comment by markuslf** [comment]
> > The plugin checks against https://endoflife.date/rhel
> 
> It ist possible to use a own website? for example
> 
> ```
>     {
>         "cycle": "88",
>         "eol": "2025-05-31",
>     },
>         {
>         "cycle": "86",
>         "eol": "2024-05-31",
>     },
>     {
>         "cycle": "84",
>         "eol": "2023-05-31",
>     },
> ```

We could add a parameter handling `Extended Life Cycle Support` from https://endoflife.date/rhel if that would help.

**Comment by markuslf** [comment]
Use `--extended-support` to check for "Extended Life Cycle Support" EOL.
