### ISSUE TITLE
about-me: Pipes ("|") within the plugin output lead to broken perfdata

### ISSUE THREAD

**Issue by K0nne** [Linuxfabrik/monitoring-plugins#741]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Pipe-symbols in the plugin output on some of our systems lead to corrupted performance data.

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/about-me

### Steps to reproduce - Data

Blurred console output   
![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/34264690/baeea331-2458-4264-9de3-88cba750df86)

icingaweb2 visualisation   
![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/34264690/39746187-44e4-43fb-8988-5708ee9ccda1)

icinga2 api output   
![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/34264690/2ddee67c-2ec5-45e6-990d-6fbe3f030795)

### Environment

Linux <hostname> 5.10.0-27-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux

### Plugin Version

about-me: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

3.9.2

**Comment by slalomsk8er** [comment]
This reminds me of https://github.com/Linuxfabrik/monitoring-plugins/issues/727

**Comment by markuslf** [comment]
Fixed in https://github.com/Linuxfabrik/lib/commit/c9072e3a537054e0c5b57899a17385f4bb860698
