### ISSUE TITLE
Grafana-Panels: No queries applied

### ISSUE THREAD

**Issue by Kaliumiodid** [Linuxfabrik/monitoring-plugins#742]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

I applied some of the dashboards via grizzly v0.2.0 (cpu-usage, memory-usage, default, icinga). All Grafana-related information seems to be imported, but the queries are missing.

### Steps to reproduce - Plugin call

gzz apply /tmp/memory-usage.yml

### Environment

grizzly 0.2.0
InfluxDB v2.x (and Flux for queries accordingly)
Grafana 10.3.

### Plugin Version

Not check-related.

**Comment by markuslf** [comment]
Did you follow https://github.com/Linuxfabrik/monitoring-plugins/blob/main/GRAFANA.rst?

**Comment by Kaliumiodid** [comment]
Yes.
For setup, I copied the provided code, the environment variables are set, the grizzly user has the editor role (with admin I get the same result). For the yml-files I copy the raw content from the files on GitHub.

**Comment by markuslf** [comment]
I've updated the GRAFANA.rst to give you a screenshot of what it should look like after installing everything in Grafana, but I'm afraid I can't help you any further here. If you need more help, we need to take a look at your installation. We can offer you this as part of [Service & Support](https://www.linuxfabrik.ch/de/produkte/service-support).

**Comment by Kaliumiodid** [comment]
Thank you for the help. I found the issue.
After looking into the Grafana log, I saw an error that the command `SHOW TAG VALUES FROM "cmd-check-about-me" WITH KEY = "hostname"` is not working. So, I created another datasource using InfluxQL instead of Flux and now it's working fine.

**Comment by markuslf** [comment]
Great! I will update the readme with your findings. Thank you.
