### ISSUE TITLE
deb-lastactivity: returns Unable to get dpkg-query info, maybe an update never happened.

### ISSUE THREAD

**Issue by withanhdammit** [Linuxfabrik/monitoring-plugins#743]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

When calling this (installed via director) it returns

Unable to get dpkg-query info, maybe an update never happened.
Traceback (most recent call last):
  File "deb-lastactivity.py", line 85, in main
ValueError: invalid literal for int() with base 10: 'icingaweb2-common'

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/deb-lastactivity

### Steps to reproduce - Data

Unable to get dpkg-query info, maybe an update never happened.
Traceback (most recent call last):
  File "deb-lastactivity.py", line 85, in main
ValueError: invalid literal for int() with base 10: 'icingaweb2-common'

### Environment

uname -a

Linux frigate 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux

### Plugin Version

deb-lastactivity: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
What output do you get running `dpkg-query --show --showformat='${db-fsys:Last-Modified} ${Package}\n'`?

**Comment by withanhdammit** [comment]
Sorry, I didn't get the notification.  This is a trim of the output:

 sudo dpkg-query --show --showformat='${db-fsys:Last-Modified} ${Package}\n'
[sudo] password for user: 
1702081306 adduser
1702081330 alsa-topology-conf
1702081330 alsa-ucm-conf
1702083656 amd64-microcode
1702081710 apache2
1702081714 apache2-bin
1702081711 apache2-data
1702081331 apache2-doc
1702083071 apache2-suexec-pristine
1702081711 apache2-utils
1702083072 apparmor
1702083072 appstream
1702081716 apt
1702077209 apt-listchanges
1702081331 apt-transport-https
1702081718 apt-utils
1702083057 aspell
1702081331 aspell-en
1702083068 attr
1707601160 base-files
1702081720 base-passwd
1702081702 bash
1702081327 bash-completion
1702081332 bc
1708747954 bind9-dnsutils
1708747954 bind9-host
1708747954 bind9-libs
1702081682 binutils
1702081685 binutils-common
1702081684 binutils-x86-64-linux-gnu
1702083071 bsdextrautils
1702081702 bsdutils
1702077780 build-essential
1702083029 busybox
1702081694 bzip2

**Comment by markuslf** [comment]
Seems that the plugin is working but it fails because of sudo. Did you configure sudo properly?

**Comment by withanhdammit** [comment]
All the other commands that use sudo work properly

**Comment by markuslf** [comment]
The plugin says `ValueError: invalid literal for int() with base 10: 'icingaweb2-common'`, but I am missing the interesting part of your output because of your trimming. It would be good to know what happens around that line (just ~10 lines around `icingaweb2-common`).

**Comment by markuslf** [comment]
Based on your report, I improved the plugin. It now warns if the last modified timestamp is not found for one or more packages.
