### ISSUE TITLE
keycloak-version: Check Keycloak Version via REST API

### ISSUE THREAD

**Issue by seraphyn** [Linuxfabrik/monitoring-plugins#748]
### Describe the solution you'd like

Hello dear Linuxfabrik team,

if Keycloak runs in a container environment, it is unfortunately not so easy to run this test, because there is no PATH in that sense.

Here the query via the [REST API](https://www.keycloak.org/docs-api/22.0.1/rest-api/index.html#RealmRepresentation) would perhaps be a good solution

All the best

Christian

**Comment by markuslf** [comment]
https://www.keycloak.org/docs-api/latest/rest-api/index.html#RealmRepresentation
