### ISSUE TITLE
about-me: expanded RAM isn't updating

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#757]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [X] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

On a VM the RAM got doubled without a reboot but a manual scheduled about-me will not report the new value.

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/about-me

### Steps to reproduce - Data

1. increase RAM of VM
2. schedule `about-me`
3. observe RAM value didn't change

### Environment

AlmaLinux 8.9 (Midnight Oncilla) Kernel 4.18.0-513.18.2.el8_9.x86_64 virtualized on vmware

### Plugin Version

about-me: v2023051201 by Linuxfabrik GmbH, Zurich/Switzerland

### Additional Information

psutil is correct but from the code I suspect dmidecode is used and this will only show the new value after a reboot.
```
$ python3
Python 3.6.8 (default, Jan 16 2024, 08:27:02)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.virtual_memory().total
67752341504
```

**Comment by markuslf** [comment]
Both values will now be reported if available. On KVM with "Current allocation: 3200 MiB" and "Maximum allocation: 3900 MiB" this will look like this: `... Current Speed: 2000 MHz, 2.9GiB/3.8GiB RAM (alloc/max), Disk vda 128G, ...`. Also now recommends rebooting if virtmem > max memory (just a hint).
