### ISSUE TITLE
Windows 'updates.exe' times out

### ISSUE THREAD

**Issue by withanhdammit** [Linuxfabrik/monitoring-plugins#761]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [X] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Windows 'updates.exe' plugin always returns a timeout.

I initially had an issue with permissions, but following [issue 695](https://github.com/Linuxfabrik/monitoring-plugins/issues/695) resolved that, but now is returning timeouts.

This happens whether run via a check, from the command line, both standard as well as elevated.
![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/16404870/1c69e94e-0db6-44e5-8c1c-a68589c1f2c6)

![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/16404870/130da78c-ee4d-4090-8eb5-990108d1a34f)

![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/16404870/03db001e-f227-41a0-b16b-8dd9dc7f9b15)

### Steps to reproduce - Plugin call

'C:\ProgramData\icinga2\usr\lib64\nagios\plugins\updates.exe' '--critical' '50' '--timeout' '300' '--warning' '2'

### Steps to reproduce - Data

Run the check whether from the Icinga2 portal or from the command line.

### Environment

Windows Server 2022, domain joined, running either via the Icinga2 check, or manually through a standard command prompt or an elevated command prompt.

### Plugin Version

updates: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

### List of Python modules

Using Windows compiled version

**Comment by markuslf** [comment]
How long does the following command take on your machine? What does it return?
```
powershell -Command "
    $WindowsUpdates = New-Object -ComObject 'Microsoft.Update.Session';
    $SearchIndex = $WindowsUpdates.CreateUpdateSearcher();
    $Pending = $SearchIndex.Search('IsInstalled=0');
    foreach ($update in $Pending.Updates) {
        [string]$name = [string]::Format('{0} [{1}]', $update.Title, $update.LastDeploymentChangeTime);
        Write-Output $name;
    }
    "

**Comment by withanhdammit** [comment]
Hi Mark,

I apologize for the late reply, apparently I did not have notifications enabled so I didn't see your reply until now.

This is from a non-elevated PowerShell prompt:
```
Get-Date

#powershell -Command "
    $WindowsUpdates = New-Object -ComObject 'Microsoft.Update.Session';
    $SearchIndex = $WindowsUpdates.CreateUpdateSearcher();
    $Pending = $SearchIndex.Search('IsInstalled=0');
    foreach ($update in $Pending.Updates) {
        [string]$name = [string]::Format('{0} [{1}]', $update.Title, $update.LastDeploymentChangeTime);
        Write-Output $name;
    }
#    "

Get-Date
```
Results:
```
Monday, June 3, 2024 6:53:49 PM
Monday, June 3, 2024 6:57:05 PM
```

**Comment by markuslf** [comment]
Try to increase the timeout by `updates --timeout 600`.
Closing this issue.

**Comment by withanhdammit** [comment]
Interestingly, the plugin does not seem to be respecting the timeout.
```
Executed Command
'C:\ProgramData\icinga2\usr\lib64\nagios\plugins\updates.exe' '--critical' '50' '--timeout' '600' '--warning' '2'
```

```
Object Properties
__name	"test-srv22.mydomain.com!Updates"
acknowledgement	1
acknowledgement_expiry	0
acknowledgement_last_change	1711757304.907525
action_url	""
active	true
check_attempt	1
check_command	cmd-check-updates-windows
check_interval	86400
check_period	""
check_timeout	10
command_endpoint	"test-srv22.mydomain.com"
display_name	"Updates"
downtime_depth	0
enable_active_checks	true
enable_event_handler	false
enable_flapping	false
```
Odd the 'check_timeout' is '10', when the command line shows '--timeout' is '600'.

**Comment by markuslf** [comment]
Yeah, seems to be an Icinga issue.
