### ISSUE TITLE
uptime: The Days, Years, Minutes etc. These values are not working

### ISSUE THREAD

**Issue by habib-ahmed-01** [Linuxfabrik/monitoring-plugins#764]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [X] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/148216438/ec0a1306-d9d6-4f53-b340-2e55443d47a0)
The uptime plugin itself works, but it is unable to take year or days or weeks or minutes information

### Steps to reproduce - Plugin call

C:\Linuxfabrik\uptime --warning=180D --critical=1Y

### Steps to reproduce - Data

Execute the plugin locally or from icinga2 with these parameters, they simply do not work!

### Environment

Windows Server 2019

### Plugin Version

uptime: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
This feature is not yet part of the released plugins, but can be found in the current main development branch (see [CHANGELOG](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CHANGELOG.md) for details). For Windows, you will have to wait for the next release.
