### ISSUE TITLE
disk-io: database error "Query failed: CREATE INDEX IF NOT EXISTS idx_79acccc6daef0f37afcb088a23702917f68d83eb ON "perfdata" (bd);, Error: no such column: bd"

### ISSUE THREAD

**Issue by K0nne** [Linuxfabrik/monitoring-plugins#774]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Since the latest update with the 2024060401 release, the check "disk-io" states:
"Query failed: CREATE INDEX IF NOT EXISTS idx_79acccc6daef0f37afcb088a23702917f68d83eb ON "perfdata" (bd);, Error: no such column: bd"

### Steps to reproduce - Plugin call

./disk-io

### Steps to reproduce - Data

Query failed: CREATE INDEX IF NOT EXISTS idx_79acccc6daef0f37afcb088a23702917f68d83eb ON "perfdata" (bd);, Error: no such column: bd

### Environment

Linux <fqdn> 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Plugin Version

disk-io: v2024040101 by Linuxfabrik GmbH, Zurich/Switzerland

### Additional Information

All affected servers are referencing the same idx-file.

**Comment by K0nne** [comment]
After inspecting the code I found a workaround:

I renamed the corrosponding sqlite-file and it was re-created as needed:
![image](https://github.com/Linuxfabrik/monitoring-plugins/assets/34264690/2cc31d37-7af8-49ff-8068-a737f38fd8e2)

Is there something wrong with the file rights?

**Comment by K0nne** [comment]
less linuxfabrik-monitoring-plugins-disk-io.db_old:

```
indexidx_79ac0823a48a22c9f93cd7000948e5372cc75b65perfdata^CCREATE INDEX idx_79ac0823a48a22c9f93cd7000948e5372cc75b65 ON "perfdata" (name)<83>^^A^G^W^]^]^A
<87>^Otableperfdataperfdata^BCREATE TABLE "perfdata" (
            name                TEXT NOT NULL,
            busy_time           INT NOT NULL,
            read_bytes          INT NOT NULL,
            read_merged_count   INT NOT NULL,
            read_time           INT NOT NULL,
            write_bytes         INT NOT NULL,
            write_merged_count  INT NOT NULL,
            write_time          INT NOT NULL,
            timestamp           INT NOT NULL
```

less linuxfabrik-monitoring-plugins-disk-io.db:

```
indexidx_79acccc6daef0f37afcb088a23702917f68d83ebperfdata^CCREATE INDEX idx_79acccc6daef0f37afcb088a23702917f68d83eb ON "perfdata" (bd)<84>2^A^G^W^]^]^A<88>7tableperfdataperfdata^BCREATE TABLE "perfdata" (
            bd                  TEXT NOT NULL,
            dmd                 TEXT,
            mp                  TEXT,
            busy_time           INT DEFAULT 0,
            read_bytes          INT DEFAULT 0,
            read_merged_count   INT DEFAULT 0,
            read_time           INT DEFAULT 0,
            write_bytes         INT DEFAULT 0,
            write_merged_count  INT DEFAULT 0,
            write_time          INT DEFAULT 0,
            timestamp           INT DEFAULT 0
```

**Comment by markuslf** [comment]
Please see https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/disk-io#troubleshooting

Since this is a bit hidden and can happen to all check plugins that use local sqlite databases, I will move this troubleshooting help to the main README.

**Comment by markuslf** [comment]
Moved to https://github.com/Linuxfabrik/monitoring-plugins?tab=readme-ov-file#tips--tricks

**Comment by jprusch** [comment]
Also came over this issue. Does it make sense to check the structure of the table & in case of an error drop & recreate?

**Comment by jprusch** [comment]
On Windows checks with a default service user (Network Service / Local System etc.) you cannot just check for $TEMP as this is user dependent. I always need admin rights & then search for the db files.... Ok, you know after the first try where to search, but this still is an extra step when updating a lot of servers.

**Comment by markuslf** [comment]
> Also came over this issue. Does it make sense to check the structure of the table & in case of an error drop & recreate?

Sounds reasonable, I will look into that.

**Comment by markuslf** [comment]
> On Windows checks with a default service user (Network Service / Local System etc.) you cannot just check for $TEMP as this is user dependent. I always need admin rights & then search for the db files.... Ok, you know after the first try where to search, but this still is an extra step when updating a lot of servers.

Thanks for the hint, will think about that.

**Comment by markuslf** [comment]
> On Windows checks with a default service user (Network Service / Local System etc.) you cannot just check for $TEMP as this is user dependent. I always need admin rights & then search for the db files.... Ok, you know after the first try where to search, but this still is an extra step when updating a lot of servers.

I double-checked: We do not use $TEMP. Instead, our libraries already use the _user's local temp directory_. On Windows this is for example `C:\\Users\\vagrant\\AppData\\Local\\Temp\\2`, on Linux it is `/tmp`.

**Comment by markuslf** [comment]
The original issue is solved, db files are now deleted on such errors and re-created by the plugins on the next run: https://github.com/Linuxfabrik/lib/commit/621a8cdd062dfeb852964779fa2bb6719b45c6de
