### ISSUE TITLE
disk-io: UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value

### ISSUE THREAD

**Issue by wwuck** [Linuxfabrik/monitoring-plugins#777]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [X] Source Code from GitHub

### Bug description

I'm trying to run `disk-io` check on lots of VMs  and on some VMs it is reporting a traceback error.

```
Traceback (most recent call last):
  File "disk-io.py", line 422, in 'module'
  File "disk-io.py", line 414, in main
  File "disk-io.py", line 183, in top
UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value
```

I set a pdb trace on the line above https://github.com/Linuxfabrik/monitoring-plugins/blob/main/check-plugins/disk-io/disk-io#L182 and get the following results:

```
(Pdb) l
181  	            )
182  	
183  	    import pdb
184  	    pdb.set_trace()
185  	
186  ->	    return msg
187  	
188  	
189  	def main():
190  	    """The main function. Hier spielt die Musik.
191  	    """
(Pdb) print(msg)
*** NameError: name 'msg' is not defined
(Pdb) print(cnt)
[('bash', {'r': 0, 'w': 0}), ('python3', {'r': 0, 'w': 0})]
```

### Steps to reproduce - Plugin call

/usr/lib64/nagios/plugins/disk-io

### Environment

# uname -a
Linux gitlab-runner-01 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

# cat /etc/os-release 
PRETTY_NAME="Devuan GNU/Linux 5 (daedalus)"
NAME="Devuan GNU/Linux"
VERSION_ID="5"
VERSION="5 (daedalus)"
VERSION_CODENAME="daedalus"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"

# cat /etc/debian_version 
12.0

# apt-cache policy linuxfabrik-monitoring-plugins 
linuxfabrik-monitoring-plugins:
  Installed: 2024060401-1
  Candidate: 2024060401-1
  Version table:
 *** 2024060401-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages
        100 /var/lib/dpkg/status
     2023112901-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages
     2023051201-1 500
        500 https://repo.linuxfabrik.ch/monitoring-plugins/debian bookworm-release/main amd64 Packages

### Plugin Version

disk-io: v2024071701 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
Perfect, thank you!
