### ISSUE TITLE
apache-httpd-status: failure when mod_md is enabled

### ISSUE THREAD

**Issue by wwuck** [Linuxfabrik/monitoring-plugins#783]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [X] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

`apache-httpd-status` check is failing when I enable `mod_md` in apache2.

https://httpd.apache.org/docs/2.4/mod/mod_md.html

https://github.com/icing/mod_md

https://icing.github.io/mod_md/

`apache-httpd-status` output:
```
Malformed Apache server info.

Traceback (most recent call last):
  File "apache-httpd-status.py", line 178, in main
ValueError: too many values to unpack (expected 2)

```

### Steps to reproduce - Plugin call

`apache-httpd-status --url=https://localhost/server-status`

### Steps to reproduce - Data

`mod_md` puts a new section into `mod_status` output:
```
ManagedCertificatesTotal: 1
ManagedCertificatesOK: 1
ManagedCertificatesRenew: 0
ManagedCertificatesErrored: 0
ManagedCertificatesReady: 0
ManagedDomain[0]Domain: example.com
ManagedDomain[0]Names[0]: example.com
ManagedDomain[0]Names[1]: www.example.com
ManagedDomain[0]Status: good
ManagedDomain[0]ValidUntil: 2024-12-17
ManagedDomain[0]CAName: LetsEncrypt
ManagedDomain[0]CAURL: https://acme-v02.api.letsencrypt.org/directory
ManagedDomain[0]: onManagedDomain[0]CheckAtType: rsa
ManagedDomain[0]CheckAtName: crt.sh
ManagedDomain[0]CheckAtURL: https://crt.sh?q=<fingerprint here>
ManagedDomain[0]CheckAtFingerprint: <fingerprint here>
ManagedDomain[0]ActivityRenew: <integer number>
ManagedStaplingsTotal: 1
ManagedStaplingsOK: 1
ManagedStaplingsRenew: 0
ManagedStaplingsErrored: 0
ManagedStapling[0]Domain: example.com
ManagedStapling[0]CertificateID: <certificate id>
ManagedStapling[0]OCSPStatus: good
ManagedStapling[0]StaplingValidUntil: 2024-10-13
ManagedStapling[0]ResponderName: r11.o.lencr.org
ManagedStapling[0]ResponderURL: http://r11.o.lencr.org
ManagedStapling[0]ActivityRefresh: <integer number>
```

### Environment

```
# apt policy apache2
apache2:
  Installed: 2.4.62-1~deb12u2
  Candidate: 2.4.62-1~deb12u2
```

### Plugin Version

apache-httpd-status: v2024031301 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
Thank you very much. I have modified the plugin to be more tolerant.

**Comment by markuslf** [comment]
> hmm is the problematic line a bug in mod_md status output?
> 
> ```
> ManagedDomain[0]: onManagedDomain[0]CheckAtType: rsa
> ```

Yes, this is exactly the problem (the plugin expected a "key: value" pair).
