### ISSUE TITLE
file-age: escaping a range starting with a minus doesn't work

### ISSUE THREAD

**Issue by slalomsk8er** [Linuxfabrik/monitoring-plugins#789]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [X] Source Code from GitHub

### Bug description

```
 '/usr/lib64/nagios/plugins/file-age' '--critical' '\-60:7200' '--critical-count' '0' '--filename
' '/mnt/some/path/*' '--only-files' '--timeout' '3' '--warning' '\-60:7200' '--warning-count' '0'
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/file-age", line 324, in 'module'
    main()
  File "/usr/lib64/nagios/plugins/file-age", line 211, in main
    if not lib.base.coe(lib.base.match_range(age, args.WARN)):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/nagios/plugins/lib/base.py", line 465, in match_range
    success, result = parse_range(spec)
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/nagios/plugins/lib/base.py", line 457, in parse_range
    start = parse_atom(start, 0)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/nagios/plugins/lib/base.py", line 437, in parse_atom
    return int(atom)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\\-60'
```
If the the minus in the range isn't escaped arg parse detects `'-60:7200'` as argument and not as a value of `'--critical'`.

### Steps to reproduce - Plugin call

'/usr/lib64/nagios/plugins/file-age' '--critical' '\-60:7200' '--critical-count' '0' '--filename ' '/mnt/some/path/*' '--only-files' '--timeout' '3' '--warning' '\-60:7200' '--warning-count' '0'

### Environment

Operating System: Debian GNU/Linux 12 (bookworm)
Kernel: Linux 6.1.0-18-amd64

### Plugin Version

file-age: v2023051201 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

3.11.2

### List of Python modules

SSSDConfig          _thread             genericpath         requests
__future__          _threading_local    getopt              resource
__hello__           _tokenize           getpass             rlcompleter
__phello__          _tracemalloc        gettext             runpy
_abc                _typing             gi                  samba
_aix_support        _uuid               glob                sched
_ast                _warnings           gpg                 secrets
_asyncio            _weakref            graphlib            select
_bisect             _weakrefset         grp                 selectors
_blake2             _xxsubinterpreters  gzip                shelve
_bootsubprocess     _xxtestfuzz         hashlib             shlex
_bz2                _zoneinfo           heapq               shutil
_codecs             abc                 hmac                signal
_codecs_cn          aifc                html                site
_codecs_hk          antigravity         http                sitecustomize
_codecs_iso2022     apt                 httplib2            six
_codecs_jp          apt_inst            idna                smtpd
_codecs_kr          apt_pkg             imaplib             smtplib
_codecs_tw          aptsources          imghdr              sndhdr
_collections        argparse            imp                 socket
_collections_abc    array               importlib           socketserver
_compat_pickle      ast                 inspect             spwd
_compression        asynchat            io                  sqlite3
_contextvars        asyncio             ipaddress           sre_compile
_crypt              asyncore            itertools           sre_constants
_csv                atexit              json                sre_parse
_ctypes             audioop             keyword             ssl
_ctypes_test        base64              ldb                 sssd
_curses             bdb                 linecache           stat
_curses_panel       binascii            locale              statistics
_datetime           bisect              logging             string
_dbm                builtins            lzma                stringprep
_dbus_bindings      bz2                 mailbox             struct
_dbus_glib_bindings cProfile            mailcap             subprocess
_decimal            calendar            marshal             sunau
_distutils_system_mod certifi             math                symtable
_elementtree        cgi                 mimetypes           sys
_functools          cgitb               mmap                sysconfig
_hashlib            chardet             modulefinder        syslog
_heapq              charset_normalizer  multiprocessing     systemd
_imp                chunk               netrc               tabnanny
_io                 cmath               nis                 talloc
_json               cmd                 nntplib             tarfile
_ldb_text           code                ntpath              tdb
_locale             codecs              nturl2path          telnetlib
_lsprof             codeop              numbers             tempfile
_lzma               collections         opcode              termios
_markupbase         colorsys            operator            test
_md5                compileall          optparse            textwrap
_multibytecodec     concurrent          os                  this
_multiprocessing    configparser        ossaudiodev         threading
_opcode             contextlib          pathlib             time
_operator           contextvars         pdb                 timeit
_osx_support        copy                pickle              token
_pickle             copyreg             pickletools         tokenize
_posixshmem         crypt               pipes               tomllib
_posixsubprocess    csv                 pkg_resources       trace
_py_abc             ctypes              pkgutil             traceback
_pydecimal          curl                platform            tracemalloc
_pyio               curses              plistlib            tty
_queue              dataclasses         poplib              turtle
_random             datetime            posix               types
_sha1               dbm                 posixpath           typing
_sha256             dbus                pprint              unicodedata
_sha3               deb822              profile             unittest
_sha512             debconf             pstats              urllib
_signal             debian              psutil              urllib3
_sitebuiltins       debian_bundle       pty                 uu
_socket             debianbts           pwd                 uuid
_sqlite3            decimal             py_compile          venv
_sre                difflib             pyclbr              warnings
_ssl                dis                 pycurl              wave
_stat               distutils           pydoc               weakref
_statistics         doctest             pydoc_data          webbrowser
_string             email               pyexpat             wsgiref
_strptime           encodings           pygtkcompat         xdrlib
_struct             enum                pyparsing           xml
_symtable           errno               pysimplesoap        xmlrpc
_sysconfigdata__linux_x86_64-linux-gnu faulthandler        pysss               xxlimited
_sysconfigdata__x86_64-linux-gnu fcntl               pysss_murmur        xxlimited_35
_tdb_text           filecmp             queue               xxsubtype
_testbuffer         fileinput           quopri              zipapp
_testcapi           fnmatch             random              zipfile
_testclinic         fractions           re                  zipimport
_testimportmultiple ftplib              readline            zlib
_testinternalcapi   functools           reportbug           zoneinfo
_testmultiphase     gc                  reprlib

**Comment by markuslf** [comment]
Explained [here](https://github.com/Linuxfabrik/monitoring-plugins?tab=readme-ov-file#command-parameters-and-arguments).

The culprit is the Icinga Director. If the Director would run the plugin with a correct parameter call of `--critical=-60:7200` (note the equal sign) it would work. I'll have to see how we can work around that, because it's just annoying.

**Comment by slalomsk8er** [comment]
How long until the director would be fixed?
Maybe striping the `\` from `-60:7200` in [match_range()](https://github.com/Linuxfabrik/lib/blob/9f0f72f22f7df13426b17aa0fa4c533c30a9ae2b/base.py#L406) could be a solution in the meantime?

**Comment by markuslf** [comment]
Library https://github.com/Linuxfabrik/lib/blob/main/base.py updated.
