### ISSUE TITLE
basket-join: json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by thesefer** [Linuxfabrik/monitoring-plugins#793]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [ ] Compiled for Windows (from download.linuxfabrik.ch)
- [X] Source Code from GitHub

### Bug description

Invalid json (https://jsonlint.com/)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8297 column 21 (char 334379)

Remove comma at lines:
- 8296
- 8664
- 8769

### Steps to reproduce - Plugin call

./tools/basket-join

### Environment

Linux alp58 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.6 LTS

### Plugin Version

basket-join: v2023112901 by Linuxfabrik GmbH, Zurich/Switzerland

### Python version

Python 3.8.10

**Comment by thesefer** [comment]
Sorry forgot to mention the file in question: `assets/icingaweb2-module-director/all-the-rest.json`

**Comment by NavidSassan** [comment]
The problem was invalid JSON in the `assets/icingaweb2-module-director/all-the-rest.json`, should be fixed now
